### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by cslamo** [soedinglab/metaeuk#1]
HI. This link in the preprint is broken: http://wwwuser.gwdg.de/~compbiol/metaeuk/2019_04

**Comment by elileka** [comment]
The right link is: http://wwwuser.gwdg.de/~compbiol/metaeuk/
Where did you find the 2019_04 one? We could not find it in the bioRxiv preprint...

**Comment by elileka** [comment]
we redirected the broken link. Thanks a lot!

**Comment by smsaladi** [comment]
Sorry for the bother, but it looks like the link is broken again. When you have a moment, would you be able to bring it back please?

**Comment by milot-mirdita** [comment]
The file server is controlled by our institutes IT. Looks like an intermittent failure there. If its not back up tomorrow, I'll try open a support ticket. Can't do anything about it currently :/

**Comment by milot-mirdita** [comment]
The server seems okay again. @smsaladi
