### ISSUE TITLE
Terrestrial arthropods

### ISSUE THREAD

**Issue by Tamtatatam** [soedinglab/metaeuk#10]
Hi

I came across MetaEuk when I was looking for tools that might allow further analysis of a metagenome dataset containing mostly (non-marine) arthropods. It looks very promising, but I understand that MetaEuk was developed for microbial eukaryotes. 

Do you think it will also work when applied to complex arthropod samples? And if so, which reference database would you recommend? I will give it a try with a small subsample, but maybe you have suggestions before I run a bigger job. 

Thanks!

**Comment by elileka** [comment]
Hello! 

We are happy that you want to give it a try!

Arthropods (Opisthokonta) are relatively well represented in public databases compared to other eukaryotic supergroups (e.g., SAR) so there should be quite a few high quality homologs to serve as reference. I think taking any big protein database, such as nr, uniprot or refseq could be a good starting point for you. In fact, it might even be worth it to subsample the big database just for the clade of arthropods or of metazoa. What I would be more cautious about is the precise exon boundaries detection. MetaEuk was not designed to learn the exact signals of transitions between introns and exons and if that is super important for you (and run time is less important), you might want to also check out tools that focus on that (e.g., running AUGUSTUS on binned contigs).

Best of luck discovering new arthropod friends!

**Comment by Tamtatatam** [comment]
Thanks! I will try uniprot with a subsample and see how it goes. The main goal is to find genes involved in functional pathways (using KEGG), so not sure if an extremely accurate prediction of exon/intron boundaries is needed (?).

Best

**Comment by elileka** [comment]
That sounds very reasonable! We've actually looked into Kegg recently ourselves by using a collection of proteins we created with MetaEuk.

Cheers
