### ISSUE TITLE
Update conda version?

### ISSUE THREAD

**Issue by berkelem** [soedinglab/metaeuk#11]
BUSCO v5 (currently in beta) uses metaeuk as a dependency. However we have noticed the bioconda version appears to be less recent than the current Github one. The conda version is missing some output files from the `easy-predict` pipeline, specifically `*.fas` and `*.codon.fas`. This presents a problem for the BUSCO conda package because the metaeuk conda package is incompatible with the BUSCO workflow that uses those output files. 

Could you please update the conda package to the latest available version?

**Comment by milot-mirdita** [comment]
Cool :) I'll make a new release this weekend.

**Comment by milot-mirdita** [comment]
Took a while longer, but here it is: https://github.com/bioconda/bioconda-recipes/pull/24991

**Comment by berkelem** [comment]
Excellent, thanks for that. It works well.
