### ISSUE TITLE
reference gene set

### ISSUE THREAD

**Issue by Francesca87** [soedinglab/metaeuk#12]
Hi there
I'd like to use MetaEuk on soil metagenomes.
I saw it expect to have a reference gene set... is this file available somewhere? How can I generate it (since I don't know which species are present)?
thanks

**Comment by milot-mirdita** [comment]
All the data we have generated for the paper is available here: http://wwwuser.gwdg.de/~compbiol/metaeuk/

**Comment by Francesca87** [comment]
Thanks! do I need to use this as reference:

MetaEuk_preds_Tara_vs_euk_profiles_uniqs.fas.gz

**Comment by elileka** [comment]
The protein profiles used in the MetaEuk paper are in [MERC_MMETSP_Uniclust50_profiles.tar.gz](http://wwwuser.gwdg.de/~compbiol/metaeuk/2019_11/MERC_MMETSP_Uniclust50_profiles.tar.gz). This is a broad protein profiles db computed from ~88 million clusters of ~330 [MERC](https://github.com/soedinglab/plass#soil-reference-catalog-src-and-marine-eukaryotic-reference-catalog-merc), MMETSP and Uniclust50 proteins.

If you are interested in specific functions, let us know. Perhaps we can assist in constructing a smaller protein or profile database focused on these.
