### ISSUE TITLE
Question: multicellular eukaryotes?

### ISSUE THREAD

**Issue by Ahmed-Shibl** [soedinglab/metaeuk#16]
Hi MetaEuk developers,

Thanks for this great tool. I'm excited to start using it soon but wanted to ask if it has been tested with multicellular eukaryotes, such as corals? and if so, which databases would be suitable to use?

Thanks in advance

**Comment by elileka** [comment]
Hello hello,

We are very happy :)

Personally, I did not try to use it for multicellular eukaryotes but I believe it is possible. Please see my answer to a similar question [here](https://github.com/soedinglab/metaeuk/issues/10).

Best of luck
