### ISSUE TITLE
Query sequence type not implemented!

### ISSUE THREAD

**Issue by Tierhon** [soedinglab/metaeuk#17]
## Expected Behavior
Successful run with predicted proteins/protein fragments

## Current Behavior
It throws an error in the prefiltering step: 
Query sequence type not implemented!

## Steps to Reproduce (for bugs)
I want to test metaeuk for annotation purposes, and want to see how it performs on a chromosome-level vertebrate genome.

I created a profile database following the instructions here: https://github.com/soedinglab/mmseqs2/wiki#how-to-create-a-target-profile-database-from-pfam, and basically just run:
easy-predict --threads 20 assembly.fasta /path_to/profileDB/pfam_profile predsResults tempFolder 

I am unsure of this is the expected command line, and especially the correct reference to the pfam_profile database. Does entries in the input contigs/assembly have to be on one line? 
 
## MetaEuk Output (for bugs)
https://gist.github.com/Tierhon/84f25355ce6758ebca4f6d47859aba80

## Context
A bit more documentation would be fine, suggested workflows for instance. GFF3 output would be great!

## Your Environment
metaeuk Version: 4.a0f584d, from conda.

Run on a large node, 120+ GB RAM etc.

Thank you.

Ole

**Comment by milot-mirdita** [comment]
Could you run:
```
xxd /cluster/projects/nn9244k/olekto/projects/annotation_pipeline/data/profileDB/pfam_profile.dbtype
xxd /cluster/work/users/olekto/test_annotation/metaeuk_profiles/tempFolder/5551969468965147792/tmp_predict/8752760177082037997/tmp_search/8988957062173247501/profileDB.dbtype
```

Something might have gone wrong when creating this Pfam.
You could use the MMseqs2/Metaeuk builtin workflow to create this Pfam:

```
metaeuk databases Pfam-A.full pfamdb tmp
```

This will automatically download and create a Pfam. The `databases` workflow is hidden in metaeuk but should still be accessible. Then you can repeat the annotation with this `pfamdb` as the target.

**Comment by Tierhon** [comment]
`xxd /cluster/projects/nn9244k/olekto/projects/annotation_pipeline/data/profileDB/pfam_profile.dbtype`
gives
`0000000: 0200 0000                                ....`
`xxd /cluster/work/users/olekto/test_annotation/metaeuk_profiles/tempFolder/5551969468965147792/tmp_predict/8752760177082037997/tmp_search/8988957062173247501/profileDB.dbtype`
gives
`0000000: 0900 0000                                ....`

Trying with the databases command now. 

Thank you.

**Comment by milot-mirdita** [comment]
Ah okay I see what's going on, MetaEuk apparently has trouble if the profile database was indexed (i.e. `createindex` was used). That's a bug on our side. You can remove the index again with:
```
rm  -f /cluster/projects/nn9244k/olekto/projects/annotation_pipeline/data/profileDB/pfam_profile.idx*
```

The index wouldn't be used in MetaEuk anyway.

**Comment by Tierhon** [comment]
Ok, great, thank you. I'll do that.

Ole

**Comment by Tierhon** [comment]
The databases command worked fine. Thank you!

**Comment by sam217pa** [comment]
Hi @milot-mirdita and thanks for metaeuk !
I ran into the same issue as Tierhon here, and deleting the idx.* file did solve the prefilter issue.

Would be great if it was mentioned in the README, for as long as the bug is unresolved ;)

Thanks again for your work on metaeuk, mmseqs and all, I use the Mmseqs2 ecosystem almost daily !
