### ISSUE TITLE
Broken MERC_MMETSP_Uniclust50_profiles.tar.gz

### ISSUE THREAD

**Issue by sarah872** [soedinglab/metaeuk#2]
Hi,
I wanted to use the profiles database that you provided on http://wwwuser.gwdg.de/~compbiol/metaeuk/2019_11/. Unfortunately the archive seems broken:

````
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
````

I tried downloading twice. Could you provide maybe a md5 sum or reupload?

**Comment by milot-mirdita** [comment]
The archive seems to be indeed broken. I'll try to rebuild it and upload it sometime later today.

**Comment by sarah872** [comment]
Great that you confirmed. Would you please let me know once you uploaded? Also, could you provide the md5 sum?

**Comment by milot-mirdita** [comment]
I regenerated the archive, tested that it extracts correctly and uploaded a MD5SUMS file containing hashes for all files. Thanks you for reporting the issue!
