### ISSUE TITLE
type of compression ?

### ISSUE THREAD

**Issue by michoug** [soedinglab/metaeuk#20]
Hi again,
I tried to the `--compressed 1` option and I got some files but I couldn't find how to uncompress them as the compression format is not clear to me.
Best
Greg

**Comment by milot-mirdita** [comment]
The `--compressed` flag comes from the MMseqs2 framework we use in the background, here we trade a bit CPU time for compressing each entry in any intermediate database we create. This can save quite a bit of disk space, but will make writing and accessing those databases a bit slower. The final result files should not be affected by this flag (if they are then thats a bug).

If you want to poke at the intermediate compressed database files, you can call `metaeuk decompress COMPRESSED_DB_IN UNCOMPESSED_DB_OUT`.

**Comment by michoug** [comment]
Hi
Thanks, the output files were also compressed hence my question as I couldn't read them.
Re-running the `unitesetstofasta` part without the `compressed` option resolved by issue

**Comment by milot-mirdita** [comment]
I fixed this behavior in 831c8975f6ea55acb4bc4f1e3605a4d1d019b66a. Using `--compressed` should not result in unreadable result files anymore.
