### ISSUE TITLE
Stop codons apparently excluded from output

### ISSUE THREAD

**Issue by nhartwic** [soedinglab/metaeuk#21]
Basically the title. I don't have a ton of experience with metaeuk and am currently using version 4.a0f584d (latest release) installed using conda. I've noticed in all of my output files that stop codons never seem to be present. Given how metaeuk works, I think I can assume that all output models have a stop codon associated with them (please confirm), but it would be nice if they were actually included in the fasta files and exon models. After all, stop codons are definitely part of the exons.

**Comment by elileka** [comment]
MetaEuk extracts putative coding fragments in all 6 frames between stop codons (or to the edge of the contig) but it considers only the part of a putative fragment that matches the target protein as the exon so the stop codon is not necessarily at the edge of the exon MetaEuk reports. Adding some info about the distance of the last stop codon from ALL exons is a good idea (thanks!). We will look into it (slowly, I am on maternity leave).

**Comment by elileka** [comment]
The option to print info about the locations of stop codons has been added. You can see it in version 9dee7a7. Thank you for the suggestion.

**Comment by nhartwic** [comment]
Thanks so much.
