### ISSUE TITLE
Easy-Predict/Reading results step error: swap results died

### ISSUE THREAD

**Issue by ys117vt** [soedinglab/metaeuk#24]
Hi everyone,

I am new to metaeuk and please help me on this issue. I was trying the easy-predict step and I used the provided reference database "MMETSP_uniclust50_MERC". However, at the last step, the system showed errors on swapresults/search step/predictexons step. Any thoughts on what is the casuse of the error message? Thank you! 

metaeuk easy-predict --threads 32 --slice-search -e 100 --metaeuk-eval 0.0001 --min-ungapped-score 35 --min-exon-aa 20 --metaeuk-tcov 0.6 --min-length 40 --disk-space-limit 200G --compressed 1 /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/final_assembly.fasta /work/cascades/.../database/MERC/MMETSP_uniclust50_MERC Metaeuk_MERC temp_MERC

MMseqs Version:                                                 4.a0f584d
Substitution matrix                                             nucl:nucleotide.out,aa:blosum62.out
Add backtrace                                                   false
Alignment mode                                                  2
Allow wrapped scoring                                           false
E-value threshold                                               100
Seq. id. threshold                                              0
Min alignment length                                            0
Seq. id. mode                                                   0
Alternative alignments                                          0
Coverage threshold                                              0
Coverage mode                                                   0
Max sequence length                                             65535
Compositional bias                                              1
Max reject                                                      2147483647
Max accept                                                      2147483647
Include identical seq. id.                                      false
Preload mode                                                    0
Pseudo count a                                                  1
Pseudo count b                                                  1.5
Score bias                                                      0
Realign hits                                                    false
Realign score bias                                              -0.2
Realign max seqs                                                2147483647
Gap open cost                                                   nucl:5,aa:11
Gap extension cost                                              nucl:2,aa:1
Zdrop                                                           40
Threads                                                         32
Compressed                                                      1
Verbosity                                                       3
Seed substitution matrix                                        nucl:nucleotide.out,aa:VTML80.out
Sensitivity                                                     4
k-mer length                                                    0
k-score                                                         2147483647
Alphabet size                                                   nucl:5,aa:21
Max results per query                                           300
Split database                                                  0
Split mode                                                      2
Split memory limit                                              0
Diagonal scoring                                                true
Exact k-mer matching                                            0
Mask residues                                                   1
Mask lower case residues                                        0
Minimum diagonal score                                          35
Spaced k-mers                                                   1
Spaced k-mer pattern
Local temporary path
Rescore mode                                                    0
Remove hits by seq. id. and coverage                            false
Sort results                                                    0
Mask profile                                                    1
Profile E-value threshold                                       0.001
Global sequence weighting                                       false
Allow deletions                                                 false
Filter MSA                                                      1
Maximum seq. id. threshold                                      0.9
Minimum seq. id.                                                0
Minimum score per column                                        -20
Minimum coverage                                                0
Select N most diverse seqs                                      1000
Min codons in orf                                               40
Max codons in length                                            32734
Max orf gaps                                                    2147483647
Contig start mode                                               2
Contig end mode                                                 2
Orf start mode                                                  1
Forward frames                                                  1,2,3
Reverse frames                                                  1,2,3
Translation table                                               1
Translate orf                                                   0
Use all table starts                                            false
Offset of numeric ids                                           0
Create lookup                                                   0
Add orf stop                                                    false
Chain overlapping alignments                                    0
Merge query                                                     1
Search type                                                     0
Search iterations                                               1
Start sensitivity                                               4
Search steps                                                    1
Slice search mode                                               true
Strand selection                                                1
LCA search mode                                                 false
Disk space limit                                                200G
MPI runner
Force restart with latest tmp                                   false
Remove temporary files                                          false
maximal combined evalue of an optimal set                       0.0001
minimal length ratio between combined optimal set and target    0.6
Maximal intron length                                           10000
Minimal intron length                                           15
Minimal exon length aa                                          20
Maximal overlap of exons                                        10
Gap open penalty                                                -1
Gap extend penalty                                              -1
allow same-strand overlaps                                      0
translate codons to AAs                                         0
write target key instead of accession                           0
Reverse AA Fragments                                            0

temp_MERC/3071197285104908048/contigs exists and will be overwritten.
createdb /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/final_assembly.fasta temp_MERC/3071197285104908048/contigs --dbtype 2 --compressed 1 -v 3

Converting sequences
[17979] 1s 649ms
Time for merging to contigs_h: 0h 0m 0s 28ms
Time for merging to contigs: 0h 0m 0s 71ms
Database type: Nucleotide
Time for processing: 0h 0m 1s 867ms
predictexons temp_MERC/3071197285104908048/contigs /work/cascades/.../database/MERC/MMETSP_uniclust50_MERC temp_MERC/3071197285104908048/MetaEuk_calls temp_MERC/3071197285104908048/tmp_predict --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 2 --wrapped-scoring 0 -e 100 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threads 32 --compressed 1 -v 3 --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -s 4 -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seqs 300 --split 0 --split-mode 2 --split-memory-limit 0 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 35 --spaced-kmer-mode 1 --rescore-mode 0 --filter-hits 0 --sort-results 0 --mask-profile 1 --e-profile 0.001 --wg 0 --allow-deletion 0 --filter-msa 1 --max-seq-id 0.9 --qid 0 --qsc -20 --cov 0 --diff 1000 --min-length 40 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 0 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --add-orf-stop 0 --chain-alignments 0 --merge-query 1 --search-type 0 --num-iterations 1 --start-sens 4 --sens-steps 1 --slice-search 1 --strand 1 --orf-filter 0 --orf-filter-e 100 --orf-filter-s 2 --lca-search 0 --disk-space-limit 200G - -force-reuse 0 --remove-tmp-files 0 --metaeuk-eval 0.0001 --metaeuk-tcov 0.6 --max-intron 10000 --min-intron 15 --min-exon-aa 20 --max-overlap 10 --set-gap-open -1 --set-gap-extend -1  --reverse-fragments 0

extractorfs /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/contigs /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/1             4365638628511940689/nucl_6f --min-length 40 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 0 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --threads 32 --compressed 1 -v 3

[=================================================================] 100.00% 18.05K 2s 675ms
Time for merging to nucl_6f_h: 0h 0m 0s 476ms
Time for merging to nucl_6f: 0h 0m 0s 658ms
Time for processing: 0h 0m 4s 467ms
translatenucs /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/nucl_6f /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MER             C/3071197285104908048/tmp_predict/14365638628511940689/aa_6f --translation-table 1 --add-orf-stop 0 -v 3 --compressed 1 --threads 32

[=================================================================] 100.00% 1.46M 22s 417ms
Time for merging to aa_6f: 0h 0m 0s 722ms
Time for processing: 0h 0m 23s 611ms
Tmp /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search folder does not exist or is not a directory.
Create dir /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search
search /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/aa_6f /work/cascades//database/MERC/MMETSP_uniclust50_MERC /wor             k/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/search_res /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104             908048/tmp_predict/14365638628511940689/tmp_search --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 2 --wrapped-scoring 0 -e 100 --min-seq-id 0 --min-aln-len 20 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb1.5 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threads 32 --compressed 1 -v 3 --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -s 4 -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seqs 300 --split 0 --split-mode 2 --split-memory-limit 0 --diag-score 1 --             exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 35 --spaced-kmer-mode 1 --rescore-mode 0 --filter-hits 0 --sort-results 0 --mask-profile 1 --e-profile 0.001 --wg 0 --allow-deletion 0 --filter-msa 1 --max-seq-id 0.9 --qid 0 --qsc -20 --cov 0 --diff 1000 --min-length 40 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-e             nd-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 0 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --add-orf-stop 0 --chain-alignments 0 --merge-query 1 --search-type 0 --num-iterations 1 --start-sens 4 --sens-steps 1 --slice-search 1 --strand 1 --orf-filter 0 --orf-filter-e 100 --orf-filter-s 2--lca-search 0 --disk-space-limit 200G --force-reuse 0 --remove-tmp-files 0

prefilter /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/profileDB /work/cascades/.../Cu             _Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/aa_6f /work/cascades/..../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365             638628511940689/tmp_search/16001091333167059095/pref --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -s 4 -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seq-len 65535 --max-seqs 2147483647 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 35 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 32 --compressed 1 -v 3

Query database size: 5894 type: Aminoacid
Estimated memory consumption: 4G
Target database size: 1457227 type: Aminoacid
Index table k-mer threshold: 127 at k-mer size 6
Index table: counting k-mers
[=================================================================] 100.00% 1.46M 8s 751ms
Index table: Masked residues: 3053013
Index table: fill
[=================================================================] 100.00% 1.46M 6s 943ms
Index statistics
Entries:          146427963
DB size:          1326 MB
Avg k-mer size:   2.287937
Top 10 k-mers
    RRRRRR      4700
    ARRRRR      3014
    RRGRRR      2726
    RPRRRR      2684
    GRRRRR      2531
    RRRRRS      2289
    RRSRRR      2122
    RRRSRR      2019
    SRRRRR      1916
    RPARRR      1873
Time for index table init: 0h 0m 16s 564ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 127
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 5894
Target db start 1 to 1457227
[=================================================================] 100.00% 5.89K 1s 49ms

48.744100 k-mers per position
21084 DB matches per sequence
0 overflows
0 queries produce too many hits (truncated result)
29 sequences passed prefiltering per query sequence
15 median result list length
323 sequences with 0 size result lists
Time for merging to pref: 0h 0m 0s 12ms
Time for processing: 0h 0m 18s 764ms
result2stats /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/profileDB /work/cascades/...             /Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/aa_6f /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14             365638628511940689/tmp_search/16001091333167059095/pref /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091             333167059095/pref_count.tsv --stat linecount --tsv --threads 32 --compressed 1 -v 3

[=================================================================] 100.00% 5.89K 0s 203ms
Time for merging to pref_count.tsv: 0h 0m 0s 14ms
Time for processing: 0h 0m 0s 238ms
align /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/profileDB /work/cascades/.../Cu_Rig             /metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/aa_6f /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/143656386             28511940689/tmp_search/16001091333167059095/pref /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 2 --wrapped-scoring 0 -e 0.439038 --min-seq-id 0 --min-aln-len 20 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threads 32 --compressed 1 -v 3

Compute score and coverage
Query database size: 5894 type: Aminoacid
Target database size: 1457227 type: Aminoacid
Calculation of alignments
[=================================================================] 100.00% 5.89K 1s 12ms
Time for merging to aln: 0h 0m 0s 12ms
176182 alignments calculated
21995 sequence pairs passed the thresholds (0.124842 of overall calculated)
3.731761 hits per query sequence
Time for processing: 0h 0m 1s 174ms
rmdb /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/pref -v 3

Time for processing: 0h 0m 0s 4ms
swapresults /work/cascades/.../database/MERC/MMETSP_uniclust50_MERC /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/aa_6f              /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln /work/cascades/.../Cu_Rig/metaeuk/AS             SEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln_swap --sub-mat nucl:nucleotide.out,aa:blosum62.out -e 3.40282e+38 --split-memory-limit 0 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --threads 32 --compressed 1 --db-load-mode 0 -v 3

Computing offsets.
[=================================================================] 100.00% 5.89K 0s 95ms

Reading results.
[=================================================================] 100.00% 5.89K 0s 87ms

Output database: /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln_swap
[=================================================================] 100.00% 1.46M 0s 927ms

Time for merging to aln_swap: 0h 0m 0s 528ms
Time for processing: 0h 1m 47s 606ms
rmdb /work/cascades.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln -v 3

Time for processing: 0h 0m 0s 2ms
mvdb /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln_swap /work/cascades/.../Cu_Rig/m             etaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln_merged -v 3

Time for processing: 0h 0m 0s 4ms
prefilter /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/profileDB /work/cascades/.../Cu             _Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/aa_6f /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365             638628511940689/tmp_search/16001091333167059095/pref --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -s 4 -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seq-len 65535 --max-seqs 2147483647 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 35 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 32 --compressed 1 -v 3

Query database size: 296204641 type: Aminoacid
Estimated memory consumption: 4G
Target database size: 1457227 type: Aminoacid
Index table k-mer threshold: 127 at k-mer size 6
Index table: counting k-mers
[=================================================================] 100.00% 1.46M 5s 841ms
Index table: Masked residues: 3053013
Index table: fill
[=================================================================] 100.00% 1.46M 7s 686ms
Index statistics
Entries:          146427963
DB size:          1326 MB
Avg k-mer size:   2.287937
Top 10 k-mers
    RRRRRR      4700
    ARRRRR      3014
    RRGRRR      2726
    RPRRRR      2684
    GRRRRR      2531
    RRRRRS      2289
    RRSRRR      2122
    RRRSRR      2019
    SRRRRR      1916
    RPARRR      1873
Time for index table init: 0h 0m 14s 356ms
Hard disk might not have enough free space (423T left).The prefilter result might need up to 16488T.
Process prefiltering step 1 of 1

k-mer similarity threshold: 127
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 296204641
Target db start 1 to 1457227
[=================================================================] 100.00% 296.20M 13h 30m 17s 881ms

48.343832 k-mers per position
20629 DB matches per sequence
3 overflows
0 queries produce too many hits (truncated result)
29 sequences passed prefiltering per query sequence
15 median result list length
15694207 sequences with 0 size result lists
Time for merging to pref: 0h 3m 11s 349ms
Time for processing: 13h 48m 40s 435ms
result2stats /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/1436563862851194                                                                                0689/tmp_search/16001091333167059095/profileDB /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/30711972851049                                                                                08048/tmp_predict/14365638628511940689/aa_6f /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908                                                                                048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/pref /work/cascades/.../Cu_Rig/metaeuk/ASSEMB                                                                                LY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/pref_count.tsv --stat linecount --tsv --threads 32 --compressed 1 -v 3

[=================================================================] 100.00% 296.20M 56m 54s 66ms
Time for merging to pref_count.tsv: 0h 3m 10s 666ms
Time for processing: 1h 2m 15s 903ms
align /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tm                                                                                p_search/16001091333167059095/profileDB /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/t                                                                                mp_predict/14365638628511940689/aa_6f /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp                                                                                _predict/14365638628511940689/tmp_search/16001091333167059095/pref /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp                                                                                _MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 2 --wrapped-scoring 0 -e 0.439038 --min-seq-id 0 --min-aln-len 20 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --max-rejected 2147483647 --max-ac                                                                                cept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --realign 0 --realign-score-b                                                                                ias -0.2 --realign-max-seqs 2147483647 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threads 32 --co                                                                                mpressed 1 -v 3

Compute score and coverage
Query database size: 296204641 type: Aminoacid
Target database size: 1457227 type: Aminoacid
Calculation of alignments
[=================================================================] 100.00% 296.20M 13h 50m 25s 685ms
Time for merging to aln: 0h 3m 50s 183ms
8604657997 alignments calculated
1048584129 sequence pairs passed the thresholds (0.121862 of overall calculated)
3.540066 hits per query sequence
Time for processing: 13h 59m 1s 474ms
rmdb /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/pref -v 3

Time for processing: 0h 0m 0s 686ms
swapresults /work/cascades/.../database/MERC/MMETSP_uniclust50_MERC /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/aa_6f /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln /work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/aln_swap --sub-mat nucl:nucleotide.out,aa:blosum62.out -e 3.40282e+38 --split-memory-limit 0 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --threads 32 --compressed 1 --db-load-mode 0 -v 3

Computing offsets.
[=================================================================] 100.00% 296.20M 19m 21s 643ms

Reading results.
/work/cascades/.../Cu_Rig/metaeuk/ASSEMBLY/temp_MERC/3071197285104908048/tmp_predict/14365638628511940689/tmp_search/16001091333167059095/searchslicedtargetprofile.sh: line 170: 17396 Killed                  "$MMSEQS" swapresults "${TARGET}" "${INPUT}" "${TMP_PATH}/aln" "${TMP_PATH}/aln_swap" ${SWAP_PAR}
Error: swapresults died
Error: search step died
Error: predictexons step died

**Comment by milot-mirdita** [comment]
That error message usually means that the linux out-of-memory killer process killed MetaEuk. What hardware are you using for this run? The `MMETSP_uniclust50_MERC` database is quite large and needs quite a bit of resources.

**Comment by milot-mirdita** [comment]
What database are you exactly searching against? It seems like your are using the raw sequences instead of the profiles. The profiles would need a lot less resources.

**Comment by ys117vt** [comment]
> That error message usually means that the linux out-of-memory killer process killed MetaEuk. What hardware are you using for this run? The `MMETSP_uniclust50_MERC` database is quite large and needs quite a bit of resources.

Hi @milot-mirdita, I am using remote university computer to run the code. For the job, I should have:

CPU: 2 x E5-2683v4 2.1GHz (Broadwell)
Cores: 32
Memories: 128 GB, 2400 MHz
LOCAL STORAGE:  1.8TB 10K RPM SAS 200 GB SSD

**Comment by ys117vt** [comment]
> What database are you exactly searching against? It seems like your are using the raw sequences instead of the profiles. The profiles would need a lot less resources.

Yes, I was using the file "MMETSP_uniclust50_MERC" which is the raw sequences I believe? So should I try the file "MMETSP_uniclust50_MERC_profile" for it? 

A side note here is for the reference database file. I should **NOT** use the compressed version right? What I did was after I downloaded the MMETSP_uniclust50_MERC.tar.gz, I extract all the files from the compressed file and only used the MMETSP_uniclust50_MERC file for my reference database. Does that sound right to you? Thanks!

Yang

**Comment by ys117vt** [comment]
> s



> Hey Yang,
> 
> Yes, this sounds right and yes, please use the **profiles** file. This should have about 88M profiles (and not 292M proteins).

Thank you @elileka! I am running it and will report when it's done.

**Comment by ys117vt** [comment]
Hi @milot-mirdita @elileka 

Just trying to follow up on this. So by using the **profiles** file, I was able to successfully finish the easy predict step. Now I am trying to directly use the output files of the 1) contigsDB 2) PredsResults.fas 3) PredsResults.headersMap. tsv to run the **taxtocontig** step. However, I got an error message as below:

"temp_tax/4143159777642653847/taxtocontig.sh: line 50:  1681 Aborted                 "$MMSEQS" swapdb "${TMP_PATH}p_num_swapped"
Error: swapdb step died
"

Should I run the step of "Creating a TSV map of predictions to their TCS group members" before the taxtocontig step? Or something else I should try?

BTW, the predsresults.headerMap.tsv is a binary file (?) and I only notice some messy codes in the file...

Thank you!
Yang

**Comment by elileka** [comment]
Hi,

predsresults.headerMap.tsv should NOT be a binary file... is it a clean run (no leftover files from previous attempts in the directory)? If not, could you please try to run easy-predict again and clean and let us know if you see a binary file?

thank you for your patience

**Comment by ys117vt** [comment]
> Hi,
> 
> predsresults.headerMap.tsv should NOT be a binary file... is it a clean run (no leftover files from previous attempts in the directory)? If not, could you please try to run easy-predict again and clean and let us know if you see a binary file?
> 
> thank you for your patience

Hi @elileka I believe it was a clean run but I will clean it up and run it again to try. Thanks for the suggestion. Will let you know how it goes. Thanks!

Yang

**Comment by ys117vt** [comment]
> > Hi,
> > predsresults.headerMap.tsv should NOT be a binary file... is it a clean run (no leftover files from previous attempts in the directory)? If not, could you please try to run easy-predict again and clean and let us know if you see a binary file?
> > thank you for your patience
> 
> Hi @elileka I believe it was a clean run but I will clean it up and run it again to try. Thanks for the suggestion. Will let you know how it goes. Thanks!
> 
> Yang

To add on this confusion :) I double checked my test run (100% clean run) with the provided contigs.fas file. The output file predict.headersMap.tsv is also a binary file...
![tsv binary file](https://user-images.githubusercontent.com/77163844/119666818-b5d8dd80-be03-11eb-85c2-9e1e65a35676.png)

**Comment by elileka** [comment]
Hi Yang,

How large is your contigs file? Is it something you could share with me? Also, could you send me a higher resolution of this screenshot? Unfortunately, I cannot read it here. You can find my email in my home page.

Thank you,
Eli

**Comment by ys117vt** [comment]
> Hi Yang,
> 
> How large is your contigs file? Is it something you could share with me? Also, could you send me a higher resolution of this screenshot? Unfortunately, I cannot read it here. You can find my email in my home page.
> 
> Thank you,
> Eli

Hi Eli,

I should mention that the contigs.fna file is actually downloaded from the test folder (https://github.com/soedinglab/metaeuk-regression/blob/d91293dd2e1e5b46ce12d986ff29740371952d4e/two_contigs/contigs.fna). And the screen shot is basically showing the system alarms me that the headersMap.tsv file may e a binary file. I will follow up with an email as well. Thanks!

Yang

**Comment by elileka** [comment]
I meant in your original run :)

**Comment by ys117vt** [comment]
> I meant in your original run :)

Just sent an email to you and please let me know if you had issue downloading the fasta file. Thank you for your help!

**Comment by milot-mirdita** [comment]
Sorry for the delay, I reproduced your issue. `--compressed` is broken in the latest release (4). It's fixed in git already (831c8975f6ea55acb4bc4f1e3605a4d1d019b66a) and the fix will be part of the next release. I didn't notice that you passed the flag, sorry that could have been a way shorter troubleshooting path :/

**Comment by ys117vt** [comment]
> Sorry for the delay, I reproduced your issue. `--compressed` is broken in the latest release (4). It's fixed in git already ([831c897](https://github.com/soedinglab/metaeuk/commit/831c8975f6ea55acb4bc4f1e3605a4d1d019b66a)) and the fix will be part of the next release. I didn't notice that you passed the flag, sorry that could have been a way shorter troubleshooting path :/

Thank you so much @milot-mirdita! I am testing it now. Will report back soon. Thank you!
Yang

**Comment by ys117vt** [comment]
> > Sorry for the delay, I reproduced your issue. `--compressed` is broken in the latest release (4). It's fixed in git already ([831c897](https://github.com/soedinglab/metaeuk/commit/831c8975f6ea55acb4bc4f1e3605a4d1d019b66a)) and the fix will be part of the next release. I didn't notice that you passed the flag, sorry that could have been a way shorter troubleshooting path :/
> 
> Thank you so much @milot-mirdita! I am testing it now. Will report back soon. Thank you!
> Yang

Hi @milot-mirdita , sorry for the delay. It took ~ 4 days to rerun the easy predict step with my fasta file. I was able to finish the easy-predict step but it failed again in the taxtocontig step with the same error code:

[===========================temp_tax/12296140655585506069/taxtocontig.sh: line 50:  3671 Segmentation fault      "$MMSEQS" swapdb "${TMP_PATH}/preds_map_num" "${TMP_PATH}/preds_map_num_swapped"
Error: swapdb step died

In addition, I noticed that the headersMp.tsv file is still a binary file with bunch of messy codes.

I am thinking am I doing this right? I was trying to use the output files from the easy-predict step to run "taxtocontig". Anything I need to do before I run the "taxtocontig" step?

**Comment by ys117vt** [comment]
> > > Sorry for the delay, I reproduced your issue. `--compressed` is broken in the latest release (4). It's fixed in git already ([831c897](https://github.com/soedinglab/metaeuk/commit/831c8975f6ea55acb4bc4f1e3605a4d1d019b66a)) and the fix will be part of the next release. I didn't notice that you passed the flag, sorry that could have been a way shorter troubleshooting path :/
> > 
> > 
> > Thank you so much @milot-mirdita! I am testing it now. Will report back soon. Thank you!
> > Yang
> 
> Hi @milot-mirdita , sorry for the delay. It took ~ 4 days to rerun the easy predict step with my fasta file. I was able to finish the easy-predict step but it failed again in the taxtocontig step with the same error code:
> 
> [===========================temp_tax/12296140655585506069/taxtocontig.sh: line 50: 3671 Segmentation fault "$MMSEQS" swapdb "${TMP_PATH}/preds_map_num" "${TMP_PATH}/preds_map_num_swapped"
> Error: swapdb step died
> 
> In addition, I noticed that the headersMp.tsv file is still a binary file with bunch of messy codes.
> 
> I am thinking am I doing this right? I was trying to use the output files from the easy-predict step to run "taxtocontig". Anything I need to do before I run the "taxtocontig" step?

Hold for my updates...I think I was still using "compressed" for my last run. Will get back soon...

**Comment by milot-mirdita** [comment]
If you didn't delete the tmp files yet, you could only rerun the last step and save quite a bit of time.

**Comment by ys117vt** [comment]
> If you didn't delete the tmp files yet, you could only rerun the last step and save quite a bit of time.

Thanks for the tips! Will try it next time :)

**Comment by ys117vt** [comment]
Hi @milot-mirdita,

I was able to run easy-predict successfully and the headers tsv file looks normal this time. Thank you again for your help! And thank you @elileka!!

I have tried the following step taxtocontig and had another error...Will open a new issue number for that one.

Yang
