### ISSUE TITLE
Taxotocontig test file run issue

### ISSUE THREAD

**Issue by ys117vt** [soedinglab/metaeuk#25]
Hi All,

I had trouble with taxtocontig step so I decided to run it again with the test file "contigs.fas" after easy-predict step. However, I got an error message as shown below:

/work/cascades/.../Cu_Rig/metaeuk/test/temp_MERC_profile/latest/contigs /work/cascades/.../Cu_Rig/metaeuk/test/M                            etaeuk_MERC_profile.fas /work/cascades/.../Cu_Rig/metaeuk/test/Metaeuk_MERC_profile.headersMap.tsv /work/cascades/.../database/tax/MMETSP_zenodo_3247846_uniclust90_2018_                            08_seed_valid_taxids tax_test_result temp_tax --majority 0.5 --tax-lineage 1 --lca-mode 2
taxtocontig /work/cascades/.../Cu_Rig/metaeuk/test/temp_MERC_profile/latest/contigs /work/cascades/.../Cu_Rig/metaeuk/test/Metaeuk_MERC_profile.fas /work/cascades/.../                            Cu_Rig/metaeuk/test/Metaeuk_MERC_profile.headersMap.tsv /work/cascades/.../database/tax/MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids tax_test_result temp_tax                             --majority 0.5 --tax-lineage 1 --lca-mode 2

MMseqs Version:                         4.a0f584d
Substitution matrix                     nucl:nucleotide.out,aa:blosum62.out
Add backtrace                           false
Alignment mode                          0
Allow wrapped scoring                   false
E-value threshold                       0.001
Seq. id. threshold                      0
Min alignment length                    0
Seq. id. mode                           0
Alternative alignments                  0
Coverage threshold                      0
Coverage mode                           0
Max sequence length                     65535
Compositional bias                      1
Max reject                              2147483647
Max accept                              2147483647
Include identical seq. id.              false
Preload mode                            0
Pseudo count a                          1
Pseudo count b                          1.5
Score bias                              0
Realign hits                            false
Realign score bias                      -0.2
Realign max seqs                        2147483647
Gap open cost                           nucl:5,aa:11
Gap extension cost                      nucl:2,aa:1
Zdrop                                   40
Threads                                 32
Compressed                              0
Verbosity                               3
Seed substitution matrix                nucl:nucleotide.out,aa:VTML80.out
Sensitivity                             4
k-mer length                            0
k-score                                 2147483647
Alphabet size                           nucl:5,aa:21
Max results per query                   300
Split database                          0
Split mode                              2
Split memory limit                      0
Diagonal scoring                        true
Exact k-mer matching                    0
Mask residues                           1
Mask lower case residues                0
Minimum diagonal score                  15
Spaced k-mers                           1
Spaced k-mer pattern
Local temporary path
Rescore mode                            0
Remove hits by seq. id. and coverage    false
Sort results                            0
Mask profile                            1
Profile E-value threshold               0.001
Global sequence weighting               false
Allow deletions                         false
Filter MSA                              1
Maximum seq. id. threshold              0.9
Minimum seq. id.                        0
Minimum score per column                -20
Minimum coverage                        0
Select N most diverse seqs              1000
Min codons in orf                       30
Max codons in length                    32734
Max orf gaps                            2147483647
Contig start mode                       2
Contig end mode                         2
Orf start mode                          1
Forward frames                          1,2,3
Reverse frames                          1,2,3
Translation table                       1
Translate orf                           0
Use all table starts                    false
Offset of numeric ids                   0
Create lookup                           0
Add orf stop                            false
Chain overlapping alignments            0
Merge query                             1
Search type                             0
Search iterations                       1
Start sensitivity                       4
Search steps                            1
Slice search mode                       false
Strand selection                        1
LCA search mode                         false
Disk space limit                        0
MPI runner
Force restart with latest tmp           false
Remove temporary files                  false
LCA ranks
Taxon blacklist                         12908,28384
Column with taxonomic lineage           1
LCA mode                                2
Taxonomy output mode                    2
Majority threshold                      0.5
Vote mode                               1

taxonomy temp_tax/6289391799667834446/preds /work/cascades/.../database/tax/MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids temp_tax/6289391799667834446/tax_per                            _pred temp_tax/6289391799667834446/tmp_taxonomy --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 0 --wrapped-scoring 0 -e 0.001 --min-seq-id 0 --min-aln-l                            en 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mo                            de 0 --pca 1 --pcb 1.5 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threa                            ds 32 --compressed 0 -v 3 --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -s 4 -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seqs 300 --split 0 --split-mode 2 --                            split-memory-limit 0 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --spaced-kmer-mode 1 --rescore-mode 0 --filter-hits 0 --sort                            -results 0 --mask-profile 1 --e-profile 0.001 --wg 0 --allow-deletion 0 --filter-msa 1 --max-seq-id 0.9 --qid 0 --qsc -20 --cov 0 --diff 1000 --min-length 30 --max-length 32                            734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 0 --us                            e-all-table-starts 0 --id-offset 0 --create-lookup 0 --add-orf-stop 0 --chain-alignments 0 --merge-query 1 --search-type 0 --num-iterations 1 --start-sens 4 --sens-steps 1 -                            -slice-search 0 --strand 1 --orf-filter 0 --orf-filter-e 100 --orf-filter-s 2 --lca-search 0 --disk-space-limit 0 --force-reuse 0 --remove-tmp-files 0 --blacklist 12908,2838                            4 --tax-lineage 1 --lca-mode 2 --tax-output-mode 2

2bLCA was replaced by Accelerated 2bLCA
extractorfs temp_tax/6289391799667834446/preds temp_tax/6289391799667834446/tmp_taxonomy/1692883838973314925/orfs_aa --min-length 30 --max-length 32734 --max-gaps 2147483647                             --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 1 --use-all-table-starts 0 --id                            -offset 0 --create-lookup 0 --threads 32 --compressed 0 -v 3

orld Size: 32 dbSize: 0
World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
3131World Size: 32 dbSize: 0
m31World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
mm39mmWorld Size: 32 dbSize: 0
31mWorld Size: 32 dbSize: 0
*** Error in `rror in `metaeukmWorld Size: 32 dbSize: 0
39mm*** Error in `metaeuk': corrupted double-linked list: 0x0000556a3d6b2070m*** Error in `World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
rror in `metaeuk': free(): corrupted unsorted chunksmmWorld Size: 32 dbSize: 0
m31World Size: 32 dbSize: 0
m31World Size: 32 dbSize: 0
31mm3939World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
orld Size: 32 dbSize: 0
3939mmmmWorld Size: 32 dbSize: 0
orld Size: 32 dbSize: 0
World Size: 32 dbSize: 0
mWorld Size: 32 dbSize: 0
World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
39morld Size: 32 dbSize: 0
mm3939morld Size: 32 dbSize: 0
mm39mError: extractorfs died
Error: taxonomy died

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## MetaEuk Output (for bugs)
Please make sure to also post the complete output of MetaEuk. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MetaEuk Version:" when you execute MetaEuk without any parameters):
* Which MetaEuk version was used (Statically-compiled, self-compiled, Homebrew, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by elileka** [comment]
If I understand correctly, you used the example file contigs.fas together with other files produced in a separate easy-predict run? If that's the case, then it makes sense taxtocontig fails because the mapping (and other files) do not match.

**Comment by ys117vt** [comment]
> Could you run the following command please and post the result here:
> 
> ```
> head -n 1 temp_tax/6289391799667834446/preds*
> ```

Hi @milot-mirdita 

I reran a clean easy-predict run with the provided test file contigs.fna and the # within the temperature folder would be different from last run but I got the same error code as:
***********************************
31mWorld Size: 32 dbSize: 0
orld Size: 32 dbSize: 0
31orld Size: 32 dbSize: 0
World Size: 32 dbSize: 0
31mWorld Size: 32 dbSize: 0
mWorld Size: 32 dbSize: 0
World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
mWorld Size: 32 dbSize: 0
31World Size: 32 dbSize: 0
World Size: 32 dbSize: 0
Error: extractorfs died
Error: taxonomy died
**************************************************************
And after running code "head -n 1 temp_tax/5506180027794825915/preds*", below is what I got:
**************************************************************
==> temp_tax/5506180027794825915/preds <==

==> temp_tax/5506180027794825915/preds.dbtype <==

==> temp_tax/5506180027794825915/preds_h <==

==> temp_tax/5506180027794825915/preds_h.dbtype <==

==> temp_tax/5506180027794825915/preds_h.index <==

==> temp_tax/5506180027794825915/preds.index <==

==> temp_tax/5506180027794825915/preds_map_num <==
▒

==> temp_tax/5506180027794825915/preds_map_num.dbtype <==

==> temp_tax/5506180027794825915/preds_map_num.index <==
0       0       3

==> temp_tax/5506180027794825915/preds_map_num_swapped.0 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.1 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.10 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.11 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.12 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.13 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.14 <==
0

==> temp_tax/5506180027794825915/preds_map_num_swapped.15 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.16 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.17 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.18 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.19 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.2 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.20 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.21 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.22 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.23 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.24 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.25 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.26 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.27 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.28 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.29 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.3 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.30 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.31 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.4 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.5 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.6 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.7 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.8 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.9 <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.dbtype <==

==> temp_tax/5506180027794825915/preds_map_num_swapped.index <==
0       0       3

==> temp_tax/5506180027794825915/preds_map_num.tsv <==
0        ▒(▒/▒P▒R
                 $p▒m▒▒L▒kػ%▒K▒qŁ$▒▒▒)gU▒Ȃ֍VBUl▒▒6+ƭ▒X▒▒D+%R▒SW▒*▒:▒m~t▒▒Hk▒m~▒▒`▒▒▒▒0▒7ʲ@|Q47h▒▒IS▒▒5▒jz▒Mo    s4▒▒ ▒▒ ▒▒'▒2▒^▒;ک▒▒▒(▒/▒P▒r▒$ `i▒▒JEMy▒tBH▒▒▒D▒P▒▒If▒▒70,▒K=▒▒▒]▒▒▒24▒▒▒▒'▒▒s▒a   }%▒▒n'▒▒>4 IT▒Q▒
                                                                                        ▒
▒C!▒▒▒▒p~▒▒▒▒▒s(UH▒▒▒(▒/▒P▒b▒$ Pi▒ Vo▒!▒        "▒n▒KT▒Ȧ$ӌ▒33▒▒n7▒uEܿ▒_ĥ▒Xm▒2▒▒  q▒▒6q   ▒▒▒▒▒l▒▒U▒7▒l▒▒B▒▒▒p▒▒+▒GAh▒a▒▒▒▒c▒▒,8▒<▒A▒b▒Ri▒b*▒)▒0▒s▒=
t▒▒▒_1▒Ef$<▒▒(▒/▒P-▒I `݀9%6▒4bg▒▒▒▒k)▒▒zG▒"▒▒e▒*k▒X▒▒¬▒▒Y▒f}f▒▒▒▒L▒▒D▒▒▒qxtd▒oz▒@g▒\▒ށ▒7E'▒▒▒▒▒▒▒jۛI▒▒b=Fl$▒▒▒7▒HD▒j,▒▒▒TK▒աY
                                                                                                                          ▒(▒/▒P=▒▒  P     ▒▒q ▒▒▒ܵH▒▒F▒TM▒▒▒▒1+▒▒▒S▒es)▒▒XV]Y▒▒\▒▒▒Np▒▒
▒s`▒▒k:˦,y▒▒▒▒M10a▒▒▒▒▒V([▒Tz*▒▒I                            }G▒@&2;▒G▒Kp▒▒

==> temp_tax/5506180027794825915/preds.source <==
0       Metaeuk_MERC.fas
**********************************************************************************************************************

**Comment by milot-mirdita** [comment]
I guess this is the same issue as before. If you run `easy-predict` or `predictexons` with `--compressed` it will produce broken output and the downstream taxonomic classification will also break.

**Comment by ys117vt** [comment]
> I guess this is the same issue as before. If you run `easy-predict` or `predictexons` with `--compressed` it will produce broken output and the downstream taxonomic classification will also break.

@milot-mirdita is right! Refer to the solved issue [https://github.com/soedinglab/metaeuk/issues/24](url)
