### ISSUE TITLE
metaeuk taxtocontig could not go through

### ISSUE THREAD

**Issue by cam315** [soedinglab/metaeuk#27]
## Expected Behavior
I am using MetaEuk (version 4.a0f584d) to do taxtocontig. The referenceDB was generated from uniref90.fasta.gz with mmseqs. The flow works fine with metaeuk easy-predict and generated files like  predsResults.codon.fas,  predsResults.fas , predsResults.headersMap.tsv. However, it reported errors saying 'latest/contigs_h!' could not be found. Could you please help me to figure it out? Thank you.

## error message

...
Loading NCBI taxonomy
Loading nodes file ... Done, got 2337542 nodes
Loading merged file ... Done, added 63247 merged nodes.
Loading names file ... Done
Making matrix ... Done
Init RMQ ...Done
Computing LCA
[=================================================================] 1.31M 0s 380ms

Taxonomy for 13761475 out of 13761475 entries not found
Time for merging to tax_per_pred: 0h 0m 0s 681ms
Time for processing: 0h 0m 6s 823ms
mvdb tempFolder/15759675103870101710/tmp_taxonomy/15765541896619596011/first tempFolder/15759675103870101710/tax_per_pred_aln -v 3

Time for processing: 0h 0m 0s 2ms
aggregatetaxweights uniprot_seqTaxDB/seqTaxDB tempFolder/15759675103870101710/preds_map_num_swapped tempFolder/15759675103870101710/tax_per_pred tempFolder/15759675103870101710/tax_per_pred_aln tempFolder/15759675103870101710/tax_per_contig --compressed 0 --majority 0.5 --vote-mode 1 --tax-lineage 1 --threads 96 -v 3

Loading NCBI taxonomy
Loading nodes file ... Done, got 2337542 nodes
Loading merged file ... Done, added 63247 merged nodes.
Loading names file ... Done
Making matrix ... Done
Init RMQ ...Done
[=================================================================] 625.42K 0s 226ms
Time for merging to tax_per_contig: 0h 0m 0s 297ms
Time for processing: 0h 0m 7s 23ms
createtsv tempFolder/15759675103870101710/preds tempFolder/15759675103870101710/tax_per_pred taxResult_tax_per_pred.tsv

Time for merging to taxResult_tax_per_pred.tsv: 0h 0m 0s 717ms
Time for processing: 0h 0m 1s 502ms
createtsv tempFolder/latest/contigs tempFolder/15759675103870101710/tax_per_contig taxResult_tax_per_contig.tsv

No datafile could be found for tempFolder/latest/contigs_h!
Error: createtsv on contigs died

**Comment by elileka** [comment]
Hi, could you please `ls` the directory `tempFolder/latest/` for us?

**Comment by DOieGYuan** [comment]
Hi, I got the same error when running taxtocontig. After the error encountered, ls the tempFolder/latest/ showed
```
preds                         tax_per_contig.12      tax_per_pred.27
preds.dbtype                  tax_per_contig.13      tax_per_pred.28
preds.index                   tax_per_contig.14      tax_per_pred.29
preds.lookup                  tax_per_contig.15      tax_per_pred.3
preds.source                  tax_per_contig.16      tax_per_pred.30
preds_h                       tax_per_contig.17      tax_per_pred.31
preds_h.dbtype                tax_per_contig.18      tax_per_pred.4
preds_h.index                 tax_per_contig.19      tax_per_pred.5
preds_map_num                 tax_per_contig.2       tax_per_pred.6
preds_map_num.dbtype          tax_per_contig.20      tax_per_pred.7
preds_map_num.index           tax_per_contig.21      tax_per_pred.8
preds_map_num.tsv             tax_per_contig.22      tax_per_pred.9
preds_map_num_swapped.0       tax_per_contig.23      tax_per_pred.dbtype
preds_map_num_swapped.1       tax_per_contig.24      tax_per_pred.index
preds_map_num_swapped.10      tax_per_contig.25      tax_per_pred_aln.0
preds_map_num_swapped.11      tax_per_contig.26      tax_per_pred_aln.1
preds_map_num_swapped.12      tax_per_contig.27      tax_per_pred_aln.10
preds_map_num_swapped.13      tax_per_contig.28      tax_per_pred_aln.11
preds_map_num_swapped.14      tax_per_contig.29      tax_per_pred_aln.12
preds_map_num_swapped.15      tax_per_contig.3       tax_per_pred_aln.13
preds_map_num_swapped.16      tax_per_contig.30      tax_per_pred_aln.14
preds_map_num_swapped.17      tax_per_contig.31      tax_per_pred_aln.15
preds_map_num_swapped.18      tax_per_contig.4       tax_per_pred_aln.16
preds_map_num_swapped.19      tax_per_contig.5       tax_per_pred_aln.17
preds_map_num_swapped.2       tax_per_contig.6       tax_per_pred_aln.18
preds_map_num_swapped.20      tax_per_contig.7       tax_per_pred_aln.19
preds_map_num_swapped.21      tax_per_contig.8       tax_per_pred_aln.2
preds_map_num_swapped.22      tax_per_contig.9       tax_per_pred_aln.20
preds_map_num_swapped.23      tax_per_contig.dbtype  tax_per_pred_aln.21
preds_map_num_swapped.24      tax_per_contig.index   tax_per_pred_aln.22
preds_map_num_swapped.25      tax_per_pred.0         tax_per_pred_aln.23
preds_map_num_swapped.26      tax_per_pred.1         tax_per_pred_aln.24
preds_map_num_swapped.27      tax_per_pred.10        tax_per_pred_aln.25
preds_map_num_swapped.28      tax_per_pred.11        tax_per_pred_aln.26
preds_map_num_swapped.29      tax_per_pred.12        tax_per_pred_aln.27
preds_map_num_swapped.3       tax_per_pred.13        tax_per_pred_aln.28
preds_map_num_swapped.30      tax_per_pred.14        tax_per_pred_aln.29
preds_map_num_swapped.31      tax_per_pred.15        tax_per_pred_aln.3
preds_map_num_swapped.4       tax_per_pred.16        tax_per_pred_aln.30
preds_map_num_swapped.5       tax_per_pred.17        tax_per_pred_aln.31
preds_map_num_swapped.6       tax_per_pred.18        tax_per_pred_aln.4
preds_map_num_swapped.7       tax_per_pred.19        tax_per_pred_aln.5
preds_map_num_swapped.8       tax_per_pred.2         tax_per_pred_aln.6
preds_map_num_swapped.9       tax_per_pred.20        tax_per_pred_aln.7
preds_map_num_swapped.dbtype  tax_per_pred.21        tax_per_pred_aln.8
preds_map_num_swapped.index   tax_per_pred.22        tax_per_pred_aln.9
tax_per_contig.0              tax_per_pred.23        tax_per_pred_aln.dbtype
tax_per_contig.1              tax_per_pred.24        tax_per_pred_aln.index
tax_per_contig.10             tax_per_pred.25        taxtocontig.sh
tax_per_contig.11             tax_per_pred.26        tmp_taxonomy
```
Thank you for your help!

**Comment by elileka** [comment]
Hi,

Indeed I cannot see the contigs_h file in this folder. This file was created by easy-predict (otherwise, it couldn't have finished its run) and should be found under the tmp_folder/latest folder of the easy-predict run. Are you running in the same directory where you ran easy-predict? Could it be that you cleaned up a bit and deleted this file? Could you please paste the full taxtocontig commad you're running?

**Comment by DOieGYuan** [comment]
Hi, thank you for your rapid reply. I ran metaeuk in batch mode for several genomes like this,
```{bash}
metaeuk easy-predict bin.1.fa MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids metaeuk_results/bin.1 metaeuk_results/tmp --threads 32

metaeuk taxtocontig metaeuk_results/tmp/latest/contigs metaeuk_results/bin.1.fas metaeuk_results/bin.1.headersMap.tsv MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids metaeuk_results/bin.1.tax metaeuk_results/tmp/ --majority 0.5 --tax-lineage 1 --lca-mode 2 --threads 32
```
Should I use different tmp directory for the two directory?

**Comment by elileka** [comment]
I think the problem might stem from the batch mode. It could be that each bin is overwriting the contigs DB (or something like that). A cleaner run will give each bin its own tmp folders. So like this:

```
metaeuk easy-predict bin.1.fa MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids metaeuk_results/bin.1 metaeuk_results/tmp1 --threads 32

metaeuk taxtocontig metaeuk_results/tmp1/latest/contigs metaeuk_results/bin.1.fas metaeuk_results/bin.1.headersMap.tsv MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids metaeuk_results/bin.1.tax metaeuk_results/tmpTax1/ --majority 0.5 --tax-lineage 1 --lca-mode 2 --threads 32
```

You can of course check this on one of your bins, first (or some other smaller input) to see if it indeed solves the problem.

**Comment by DOieGYuan** [comment]
> I think the problem might stem from the batch mode. It could be that each bin is overwriting the contigs DB (or something like that). A cleaner run will give each bin its own tmp folders. So like this:
> 
> ```
> metaeuk easy-predict bin.1.fa MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids metaeuk_results/bin.1 metaeuk_results/tmp1 --threads 32
> 
> metaeuk taxtocontig metaeuk_results/tmp1/latest/contigs metaeuk_results/bin.1.fas metaeuk_results/bin.1.headersMap.tsv MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids metaeuk_results/bin.1.tax metaeuk_results/tmpTax1/ --majority 0.5 --tax-lineage 1 --lca-mode 2 --threads 32
> ```
> 
> You can of course check this on one of your bins, first (or some other smaller input) to see if it indeed solves the problem.

Yes, use different --tmpdir for easy-predict and taxtocontig can solve this problem. Thank you for your kind help.

**Comment by elileka** [comment]
With pleasure. I am closing the issue. If you encounter further problems, you can always reopen it or open a new issue.
