### ISSUE TITLE
Can this be used with transcript contigs?

### ISSUE THREAD

**Issue by jolespin** [soedinglab/metaeuk#28]
I ran rnaSPAdes and was wondering if I could use MetaEuk for gene calls.

**Comment by elileka** [comment]
Hello, 
I am not familiar exactly with the specific output of rnaSPAdes but in general, if there is protein-coding information in your data, MetaEuk should be able to detect it given that there are homologs in the target database. Please note that if your data is of processed RNA, it can be that an originally multiexon gene appears as a "single exon". For the same reason, be careful when interpreting frame and strand for the same reason. In the MetaEuk header all positions will be with respect to the contig, so in your case, RNA.

**Comment by jolespin** [comment]
If you are running this on multiple MAGs, does it make any difference in the predictions if all MAGs are concatenated into a single fasta file or should they be kept separate?

**Comment by elileka** [comment]
You can provide your sequences in a single file. MetaEuk treats each sequence in the Fasta input as a single contig (so in a very perfect world, as a whole genome). It thus does not reduce redundancy between contigs or anything like that.
