### ISSUE TITLE
How to visualize metaeuk results?

### ISSUE THREAD

**Issue by JSSaini** [soedinglab/metaeuk#29]

**Comment by elileka** [comment]
The results of easy-predict are given in a Fasta file, without any visualization. @Andy-B-123 wrote a Python script that allows converting them to a GFF format. See [here](https://github.com/soedinglab/metaeuk/issues/4#issuecomment-766574620).

The results of easy-taxonomy can be converted into Krona or Kraken plots. See details [here](https://github.com/soedinglab/MMseqs2/wiki#taxonomy-report-in-kraken-or-krona-style).

**Comment by elileka** [comment]
GFF output is part of [release 5-34c21f2](https://github.com/soedinglab/metaeuk/releases/tag/5-34c21f2)
