### ISSUE TITLE
Taxdatabase error

### ISSUE THREAD

**Issue by H1889** [soedinglab/metaeuk#31]
Hi,

First of all, thank you for your nice Metauk pipeline, I have installed it with Uniref100 database following the instructions at github. However when I run the contigtotax command an error is shown:
 
"Database UniRef100NoQUE need taxonomical information.
The UniRef100NoQUE_nodes.dmp is missing."

However the UniRef100NoQUE_taxonomy file is there.

These are my files at my working directory where I run metaeuk:

tmp
UniRef100NoQUE_taxonomy
UniRef100NoQUE_mapping
UniRef100NoQUE_h.index
UniRef100NoQUE_h.dbtype
UniRef100NoQUE_h
UniRef100NoQUE.source
UniRef100NoQUE.lookup
UniRef100NoQUE.index
UniRef100NoQUE.dbtype
UniRef100NoQUE
UniRef100_taxonomy
UniRef100_mapping
UniRef100_h.index
UniRef100_h.dbtype
UniRef100_h
UniRef100.version
UniRef100.source
UniRef100.lookup
UniRef100.index
UniRef100.dbtype
UniRef100
QUEMETAEUK.headersMap.tsv
QUEMETAEUK.fas
QUEMETAEUK.codon.fas

My command was:
metaeuk taxtocontig tmp/latest/contigs QUEMETAEUK.fas QUEMETAEUK.headersMap.tsv UniRef100NoQUE QUEMETAEUK_TAX tmp --majority 0.5 --tax-lineage 1 --lca-mode 2

Surely I am making some mistake but I can not see it,I would be very grateful if you could help me to solve it.

**Comment by elileka** [comment]
Hi,

Thank you for using MetaEuk.
From the files in your directory it seems that indeed the nodes file is missing as the software complains. How did you obtain that database? Could you please try obtaining it by running `metaeuk databases UniRef100 UniRef100DB tmp` and using the downloaded `UniRef100DB`? It should be accompanied with all required files.

**Comment by H1889** [comment]
Thanks for the answer, These were my commnads:
mmseqs databases UniRef100 UniRef100 tmp
mmseqs createtaxdb UniRef100 tmp

But *_taxonomy file is a binnary file with all requiered *.dmp files, is not it?

**Comment by H1889** [comment]
From mmseq2 help:
An MMseqs2 database seqTaxDB is a sequence database augmented with taxonomic information and a mapping file from each database key to its taxon id. Such a database includes the following files: seqTaxDB, seqTaxDB.index, seqTaxDB.dbtype, seqTaxDB.lookup, seqTaxDB_h, seqTaxDB_h.index, seqTaxDB_h.dbtype, seqTaxDB_mapping and either the taxonomy flat file databases seqTaxDB_nodes.dmp, seqTaxDB_names.dmp, seqTaxDB_merged.dmp o**r seqTaxDB_taxonomy a binary version of the former files (created by createtaxdb which reduces the read-in time of the taxonomy databas**e).

**Comment by milot-mirdita** [comment]
Are you using the latest release or the compiling from the latest git code? The issue might have been fixed already in git.

**Comment by milot-mirdita** [comment]
You can download precompiled binaries from the latest git code here: https://mmseqs.com/metaeuk/
Could you please check if the error message persists with this binary?

**Comment by milot-mirdita** [comment]
I just checked, we indeed fixed the issue already in git. We will prepare a new release with the fix.

In the meantime, you can do:
```
touch UniRef100NoQUE_nodes.dmp
touch UniRef100NoQUE_names.dmp
touch UniRef100NoQUE_merged.dmp
```

This will defeat the check, but it will still prefer the functional `_taxonomy` file over the dummy `.dmp` files.

**Comment by H1889** [comment]
I installed it with conda, both mmseqs2 and metaeuk

**Comment by H1889** [comment]
my installed versions:
MMseqs2 Version: 13.45111
metaeuk Version: 4.a0f584d

**Comment by H1889** [comment]
Given I have downloaded the Uniref100, can I use it? If a I run metaeuk databases UniRef100 UniRef100DB tmp it starts to dowload it again

**Comment by milot-mirdita** [comment]
You can manually download the ncbi taxdump file: https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
Extract the `names.dmp nodes.dmp merged.dmp` files and place them under 
```
UniRef100DB_names.dmp
UniRef100DB_nodes.dmp
UniRef100DB_merged.dmp
```

**Comment by H1889** [comment]
Thank you, that worked. A final question, my assembly has 23000 contigs, however only 12000 have been tax annotated by the contigtotax command, that means that metauk can not assign a tax to 11000 contigs?

**Comment by H1889** [comment]
The *_tax_per_contig.tsv has exactly 12413 contigs however the input metagenome had 23344

**Comment by elileka** [comment]
> Thank you, that worked. A final question, my assembly has 23000 contigs, however only 12000 have been tax annotated by the taxtocontig command, that means that metaeuk can not assign a tax to 11000 contigs?

Yes, exactly.
