### ISSUE TITLE
[Feature Request] Custom protein and codon file extensions (and GFF?) and few minor questions

### ISSUE THREAD

**Issue by jolespin** [soedinglab/metaeuk#32]
I'm trying to integrate this into some pipelines at JCVI and I have to make a lot of post hoc "helper scripts" to do some post-processing.

I wanted to run a few minor feature requests by you:
1. Custom codon (DNA) file extensions (e.g. ffn)
2. Custon protein file extensions (e.g. faa)
3. Also include a GFF file so it can be more easily integrated into pipelines that use prodigal, STAR/HISAT2, and featureCounts.  It wouldn't have to replace the headerMap.tsv but it could be included in addition to that even with a --gff argument.  At the very least, a test headerMap.tsv -> GFF script that gets installed with the package. 

Questions: 
1. What is the preferred file extension for. MMSEQS2 databases? For example, if you have an uncompressed protein fasta file called `nr` would you use file extension `nr.mmseqs` like w/ diamond who it would be `nr.dmnd`? 
2. Does MMSEQS2 return multiple isoforms for the same gene? 
3. Would you advise against renaming some of the proteins in a more filename friendly format like prodigal (potentially because of [2] above)? For example, `AYO43713.1|NODE_2835_length_4878_cov_5.258553|+|1910|0|1|1386|4418|1386[1386]:4418[4418]:3033[3033]` -> `NODE_2835_length_4878_cov_5.258553_1`

**Comment by elileka** [comment]
Hi,

Thank you for the helpful feedback!

Concerning GFF, @Andy-B-123 has written a Python script that allows converting them to a GFF format. See [here](https://github.com/soedinglab/metaeuk/issues/4#issuecomment-766574620). 

As for your questions:
1. MMseqs2 and MetaEuk do not require a specific file ending. The `createdb` command creates a file in the format of MMseqs2/MetaEuk by the name you give it.
2. MetaEuk does not report isoformas of the same gene. This means that if E1+E2+E3 matched some reference protein but also E1+E3 matched another reference protein (an isoform) than only E1+E2+E3 will be reported (assuming it has a better E-value than E1+E3). This occurs at the redundancy reduction stage.
3. You can name as you see fit, of course. Just note that the unique combination would be the T+C+S (so in the example you gave `AYO43713.1|NODE_2835_length_4878_cov_5.258553|+`). I think it is better to take that into account when numbering.

**Comment by jolespin** [comment]
>Concerning GFF, @Andy-B-123 has written a Python script that allows converting them to a GFF format. See here.
I'll definitely check this out.  Do you have any plans to integrate an official script that does this? I'm hoping that people start paying more attention to euks with all these new tools coming out addressing different issues and feel like this type of output will be requested by others as well.  `MetaEuk` is definitely by far the most streamlined and easy to use tool (thank you again for making this!) so I'm assuming a lot of people will catch on. 

>MMseqs2 and MetaEuk do not require a specific file ending. The createdb command creates a file in the format of MMseqs2/MetaEuk by the name you give it.

K this good to know.  I guess it was more of a "stylistic" question and asking what you as the developer generally uses.  Do you just use the actual fasta name since it adds a bunch of files that suffixed with that basename?  Similar to doing `bowtie2-build input.fasta input.fasta` makes a bunch of `input.fasta.bt2.*` index files. 

>MetaEuk does not report isoformas of the same gene. This means that if E1+E2+E3 matched some reference protein but also E1+E3 matched another reference protein (an isoform) than only E1+E2+E3 will be reported (assuming it has a better E-value than E1+E3). This occurs at the redundancy reduction stage.
Great this makes it a lot easier. 

>You can name as you see fit, of course. Just note that the unique combination would be the T+C+S (so in the example you gave AYO43713.1|NODE_2835_length_4878_cov_5.258553|+). I think it is better to take that into account when numbering.
Apologies but can you elaborate a little more on this?

**Comment by elileka** [comment]
I am sorry. I think I wasn't clear enough. The TCS refers to the 'Target', 'Contig' and 'Strand' combination.  We write about it here: https://github.com/soedinglab/metaeuk#terminology. As more than one prediction can be made on a contig and more than one contig can have a prediction based on the same target, the unique identifier is a combination of the three.

I now added GFF output to MetaEuk. I still need to test it a bit but maybe you'd like to have a look too? It is not part of a release so it's not available through conda yet. I followed @Andy-B-123 idea about the meaning of 'exon' and 'CDS'. I still haven't added any description of it to the README.

**Comment by elileka** [comment]
Please see [release 5-34c21f2](https://github.com/soedinglab/metaeuk/releases/tag/5-34c21f2)

**Comment by jolespin** [comment]
Not sure if this helps but I've made script that does the following: 

1) Simplifies the identifiers; 
2) Provides custom extensions for cds and protein; 
3) Recreates the GFF file entirely and add exon identifiers

I've done this to more easily integrate MetaEuk output into my pipeline that is dependent on prodigal. 

```python 
#!/usr/bin/env python
import sys, os, glob, argparse 
from itertools import groupby 
from collections import OrderedDict
import pandas as pd
from Bio.SeqIO.FastaIO import SimpleFastaParser

__program__ = os.path.split(sys.argv[0])[-1]
__version__ = "2022.03.03"

def simplify_metaeuk_identifiers(identifiers):
    def f_sort(id):
        fields = id.split("|")
        start = int(fields[6])
        end = int(fields[7])
        return (start, end)
    
    metaeuk_to_simple = dict()
    for id_contig, contig_orf_ids in groupby(identifiers, key=lambda x: x.split("|")[1]):
        metaeuk_identifiers = sorted(contig_orf_ids, key=f_sort)
        simple_identifiers = map(lambda i: "{}_{}".format(id_contig, i), range(1, len(metaeuk_identifiers)+1))
        metaeuk_to_simple.update(dict(zip(metaeuk_identifiers, simple_identifiers)))
    return pd.Series(metaeuk_to_simple)

def main(argv=None):
    # Path info
    script_directory  =  os.path.dirname(os.path.abspath( __file__ ))
    script_filename = __program__
    # Path info
    description = """
    Running: {} v{} via Python v{} | {}""".format(__program__, __version__, sys.version.split(" ")[0], sys.executable)
    usage = "{} -i <scaffold_to_mag> -c <mag_to_clusters.tsv> -o <output_filepath>".format(__program__)
    epilog = "Copyright 2022 Josh L. Espinoza (jespinoz@jcvi.org)"

    # Parser
    parser = argparse.ArgumentParser(description=description, usage=usage, epilog=epilog, formatter_class=argparse.RawTextHelpFormatter)
    # Pipeline
    parser.add_argument("-d","--cds", type=str, required=True, help = "path/to/output.codons.fsa")
    parser.add_argument("-a","--protein", type=str, required=True, help = "path/to/output.fsa")
    parser.add_argument("-o","--output_directory", type=str, default="metaeuk_output", help = "path/to/output_directory [Default: metaeuk_output]")
    parser.add_argument("-b", "--basename", type=str, default="gene_models", help = "Base name for gene models [Default: gene_models]")

    parser.add_argument("--no_header", action="store_true", help="Specify if header should not be in fasta files")
    parser.add_argument("--cds_extension", type=str, default="ffn", help = "CDS fasta extension [Default: ffn]")
    parser.add_argument("--protein_extension", type=str, default="faa", help = "Protein fasta extension [Default: faa]")

    # Options
    opts = parser.parse_args(argv)
    opts.script_directory  = script_directory
    opts.script_filename = script_filename

    # Output directory
    os.makedirs(opts.output_directory, exist_ok=True)

    # Load in CDS sequences
    id_to_seq = OrderedDict()
    with open(opts.cds, "r") as f:
        for header, seq in SimpleFastaParser(f):
            id = header.split(" ")[0]
            id_to_seq[id] = seq
    cds_sequences = pd.Series(id_to_seq)

    # Load in protein sequences
    id_to_seq = OrderedDict()
    with open(opts.protein, "r") as f:
        for header, seq in SimpleFastaParser(f):
            id = header.split(" ")[0]
            id_to_seq[id] = seq
    protein_sequences = pd.Series(id_to_seq)

    # Convert MetaEuk to simple identifiers
    metaeuk_to_simple = simplify_metaeuk_identifiers(cds_sequences.index)

    # Relabel identifiers
    if opts.no_header:
        cds_sequences.index = cds_sequences.index.map(lambda id_metaeuk: metaeuk_to_simple[id_metaeuk])
        protein_sequences.index = protein_sequences.index.map(lambda id_metaeuk: metaeuk_to_simple[id_metaeuk])
    else:
        cds_sequences.index = cds_sequences.index.map(lambda id_metaeuk: "{} {}".format(metaeuk_to_simple[id_metaeuk], id_metaeuk))
        protein_sequences.index = protein_sequences.index.map(lambda id_metaeuk: "{} {}".format(metaeuk_to_simple[id_metaeuk], id_metaeuk))


    gff_output = list()
    for id_metaeuk, id_gene in metaeuk_to_simple.items():
        metaeuk_fields = id_metaeuk.split("|")
        
        # Gene
        id_target = metaeuk_fields[0]
        id_contig = metaeuk_fields[1]
        strand = metaeuk_fields[2]
        id_tcs = "|".join([id_target, id_contig, strand])

        start_gene = int(metaeuk_fields[6]) + 1
        end_gene = int(metaeuk_fields[7]) + 1
        bitscore = float(metaeuk_fields[3])
        gene_description = "target_id={};tcs_id={};contig_id={};gene_id={};".format(
            id_target,
            id_tcs,
            id_contig,
            id_gene,
        )
        gene_fields = [id_contig, "MetaEuk", "gene", start_gene, end_gene, bitscore, strand, ".", gene_description]

        # gff_output.append("\t".join(map(str, gene_fields)))
        gff_output.append(gene_fields)

        # mRNA
        mrna_description = "target_id={};tcs_id={};contig_id={};gene_id={};Parent={};".format(
            id_target,
            id_tcs,
            id_contig,
            id_gene,
            id_gene,
        )
        mrna_fields = [id_contig, "MetaEuk", "mRNA", start_gene, end_gene, bitscore, strand, ".", mrna_description]

        # gff_output.append("\t".join(map(str, mrna_fields)))
        gff_output.append(mrna_fields)

        # Exons
        for i, exon in enumerate(metaeuk_fields[8:], start=1):
            exon_fields = exon.split(":")
            start_exon = int(exon_fields[0].split("[")[0]) + 1
            end_exon = int(exon_fields[1].split("[")[0]) + 1
            id_exon = "{}.{}".format(id_gene, i)

            exon_description = "target_id={};tcs_id={};contig_id={};gene_id={};Parent={};exon_id={}".format(
                id_target,
                id_tcs,
                id_contig,
                id_gene,
                id_gene,
                id_exon,
            )
            exon_fields = [id_contig, "MetaEuk", "exon", start_exon, end_exon, bitscore, strand, ".", exon_description]
            gff_output.append(exon_fields)
            # output.append("\t".join(map(str, exon_fields)))

    df_gff = pd.DataFrame(gff_output)

    # Write output

    # Identifiers
    metaeuk_to_simple.to_frame().to_csv(os.path.join(opts.output_directory,"identifier_mapping.tsv"), sep="\t", header=False)

    # CDS
    with open(os.path.join(opts.output_directory,"{}.{}".format(opts.basename, opts.cds_extension)) , "w") as f:
        f.writelines(">{}\n{}\n".format(id, seq) for id, seq in cds_sequences.items())

    # Protein
    with open(os.path.join(opts.output_directory,"{}.{}".format(opts.basename, opts.protein_extension)) , "w") as f:
        f.writelines(">{}\n{}\n".format(id, seq) for id, seq in protein_sequences.items())
    # GFF
    df_gff.to_csv(os.path.join(opts.output_directory,"{}.gff".format(opts.basename)), sep="\t", index=False, header=False)
    
if __name__ == "__main__":
    main()

```
