### ISSUE TITLE
I can't find 'contigs' output to pass to taxtocontig

### ISSUE THREAD

**Issue by drelo** [soedinglab/metaeuk#39]
## Expected Behavior

Dear all,  I used MetaEuk in the past but I am trying to search Eukaryotes in another dataset. I run the easy-predict stage with no apparent issues I got the .fas and the tsv file (I am attaching both)

## Steps to Reproduce (for bugs)

I downloaded the trembl database first

`mmseqs databases UniProtKB/TrEMBL db/trembl tmp
`

Then:

`mmseqs createdb ./DATA/sample.fas ./DATA/sample_db`
`easy-predict DATA/sample_db db/trembl predsResults tempFolder --threads 10`

The following stage should be something like this code

`metaeuks taxtocontig ./tempFolder/latest/contigs predResults.fas predsResults.headersMap.tsv ./db/trmbl taxResult.tsv 
 tmptaxtocontig --majority 0.5 --tax-lineage 1 --lca-mode 2`

Maybe I missed something but now I can't find the contigs in the tempFolder.
I will try to rerun this trying to diagnose this but I thought any help would be appreciated. Thanks in advance

Andrés Parada

## MetaEuk Output (for bugs)
Please make sure to also post the complete output of MetaEuk. You can use gist.github.com for large output.

Here is the content of the tempFolder:

```
easypredict.sh   MetaEuk_calls.6       MetaEuk_preds.1  MetaEuk_preds.8        MetaEuk_preds_clust.5       MetaEuk_preds.dbtype
MetaEuk_calls.0  MetaEuk_calls.7       MetaEuk_preds.2  MetaEuk_preds.9        MetaEuk_preds_clust.6       MetaEuk_preds.index
MetaEuk_calls.1  MetaEuk_calls.8       MetaEuk_preds.3  MetaEuk_preds_clust.0  MetaEuk_preds_clust.7       tmp_predict
MetaEuk_calls.2  MetaEuk_calls.9       MetaEuk_preds.4  MetaEuk_preds_clust.1  MetaEuk_preds_clust.8
MetaEuk_calls.3  MetaEuk_calls.dbtype  MetaEuk_preds.5  MetaEuk_preds_clust.2  MetaEuk_preds_clust.9
MetaEuk_calls.4  MetaEuk_calls.index   MetaEuk_preds.6  MetaEuk_preds_clust.3  MetaEuk_preds_clust.dbtype
MetaEuk_calls.5  MetaEuk_preds.0       MetaEuk_preds.7  MetaEuk_preds_clust.4  MetaEuk_preds_clust.index
```

## Context

[In case it helps I am uploading the log from the easy-predict search, the output as .fas and a .tsv file here](https://drive.google.com/drive/folders/1ma8pkTGEw7T8nziEDQ3znsW_Qq5lC5DE?usp=sharing).

## Your Environment

* Which MetaEuk version was used
Statically-compiled metaeuk-linux-sse41 metaeuk Version: 9818d1a5b155c28b3ef11bfa9b7c69073e669a70
conda version of mmseqs == MMseqs2 Version: 13.45111

* Operating system and version:
CentOS-8

**Comment by drelo** [comment]
Sorry to bother you again, I tried to reproduce the error using the [contigs.fna file provided here](https://github.com/soedinglab/metaeuk-regression/tree/640451971df508c51392fe7150ff0e0aaf5b65cf/two_contigs) and I also end with a temporal folder with no contigs to use in the taxtocontig step. The easy-predict seemed to work since I got a prediction like this in the `.tsv` file. 

> 0       100+1042        0       28388527        1       S9PRI6|my_multi_exon_contig_1|+|494|3.065e-138|3|100|1141|100[100]:429[429]:330[330]|480[480]:881[881]:402[402]|962[962]:1141[1141]:180[180]

Any help would be appreciated. 
Best regards

Andrés

**Comment by elileka** [comment]
Hello,

In your case it seems like you create the contigs database at the first step with the command:
```mmseqs createdb ./DATA/sample.fas ./DATA/sample_db```
So that means that instead of `contigs` you need to provide `DATA/sample_db` to taxtocontig.

It's a bit confusing but that's because easy-predict can also run directly on FASTA (in which case it will first create a db and call it by the very creative name `contigs`).

I am guessing you did the same with the dummy example too because I could not reproduce it on my side (i.e., if I only run easy-predict I find the `contigs` db)

**Comment by drelo** [comment]
I got confused by the instructions `metaeuk easy-predict contigsFasta/contigsDB...` so I build the db with mmseqs as I used to.
I fixed and it worked fine. Thanks for your help!
