### ISSUE TITLE
Add option to output a GFF3 file

### ISSUE THREAD

**Issue by apcamargo** [soedinglab/metaeuk#4]
It would be very useful if MetaEuk could output a GFF3 file, like most gene prediction software This would make it easier to integrate MetaEuk into annotation pipelines.

Currently, the user would need to parse the output FASTA file, but this can be tricky if the database sequences have `|` in their names and the genes have multiple exons.

**Comment by Andy-B-123** [comment]
Hi, I was after this feature as well and wrote a not-very-elegant python script to do this. It takes the information from the header for each fasta and processes it to gff3 format. 

It does require the database sequences not to use '|' as I use this character to split the fields in the header. It can handle any number of exons. I've tested it with some annotations and it seems to work to annotate the output fasta sequences on the original contigs:

https://github.com/Andy-B-123/LittleScripts/blob/main/MetaeukToGff3.py

**Comment by elileka** [comment]
Please see [release 5-34c21f2](https://github.com/soedinglab/metaeuk/releases/tag/5-34c21f2)
