### ISSUE TITLE
Request for better documentation of aggregatetax module

### ISSUE THREAD

**Issue by IanDMedeiros** [soedinglab/metaeuk#42]
## Expected Behavior
I want to re-run aggregatetax with different parameters on a sample for which I already ran taxtocontig.

## Current Behavior
The help page for aggregatetax includes an input "setToSeqMap" that I cannot find mentioned in the documentation for any other module I used to get to this point in the analysis. I am not sure which of the intermediate files or databases this refers to. 

## Your Environment
* metaeuk Version: 4.a0f584d
* set up through bioconda 
* Operating system and version: Running on HPC cluster with RHL-18

**Comment by IanDMedeiros** [comment]
I have continued looking into this and it seems like I should actually be using aggregatetaxweights? The Metaeuk manual doesn't say anything about this but I was initially going off of the comment in the mmseqs2 manual that "For nucleotide-protein searches (contig taxonomy assignment) the final output is generated by the aggregatetax module, and therefore more context is provided." 

The --help page for aggregatetaxweights that is similar to aggregatetax, but in the file taxtocontig.sh I see 

`aggregatetaxweights "${TAX_TARGET_DB}" "${TMP_PATH}/preds_map_num_swapped" "${TMP_PATH}/tax_per_pred" "${TMP_PATH}/tax_per_pred_aln" "${TMP_PATH}/tax_per_contig" ${AGGREGATETAX_PAR}`

So, setToSeqMap = preds_map_num_swapped?

It would be helpful to have clearer documentation for folks who want to only rerun the summary with, say, a different value for --tax-lineage or --majority.

**Comment by elileka** [comment]
Thank you for the comment. When we developed this module, we thought of it as an internal module and they are not as well documented as the workflows. However, your use-case makes a lot of sense. I will need to give it some attention in the future.
As for your specific questions: yes, aggregatetaxweights is the function to call. It takes into account the (minus log) e-values of the individual hits so the voting is weighted accordingly. 
And yes, setToSeqMap = preds_map_num_swapped. In addition to your taxonomy reference db, you should be able to find all other needed input files in your TMP_PATH and then you can change the parameters of the command. Can you `ls` your TMP_PATH/latest?
Don't forget to change the output name so you don't override the previous run `"${TMP_PATH}/tax_per_contig_new_run"`

**Comment by IanDMedeiros** [comment]
Thank you. Once I saw how aggregatetaxweights was called in taxtocontig.sh I was able to figure out how to get the output I needed.
