### ISSUE TITLE
threads of metaeuk

### ISSUE THREAD

**Issue by Fang-Liu-CAS** [soedinglab/metaeuk#54]
## Expected Behavior
Is it allowed to setup threads when running metaeuk?
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## MetaEuk Output (for bugs)
Please make sure to also post the complete output of MetaEuk. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MetaEuk Version:" when you execute MetaEuk without any parameters):
* Which MetaEuk version was used (Statically-compiled, self-compiled, Homebrew, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by milot-mirdita** [comment]
Metaeuk uses by default all CPU cores available on the system. You can limit the number of threads with the `--threads` parameter.

**Comment by Fang-Liu-CAS** [comment]
> Metaeuk uses by default all CPU cores available on the system. You can limit the number of threads with the `--threads` parameter.

Thanks a lot for your reply. It works now.
