### ISSUE TITLE
Running easy-predict with profiles and multiple iterations does not work

### ISSUE THREAD

**Issue by olekto** [soedinglab/metaeuk#56]
## Expected Behavior
GFF with the found profiles.

## Current Behavior
Stopping at collectoptimalset step.

## Steps to Reproduce (for bugs)
easy-predict --num-iterations 2 --metaeuk-tcov 0.4 --metaeuk-eval 1 -s 7.5 --max-seqs 5000 --max-intron 200000 --threads 20 assembly.fasta /cluster/projects/nn8013k/opt/profileDB/pfam_profile predsResults_s7.5_5k_ni2_slice_mt0.4_me1 tempFolder 

## MetaEuk Output (for bugs)
easy-predict --num-iterations 2 --metaeuk-tcov 0.4 --metaeuk-eval 1 -s 7.5 --max-seqs 5000 --max-intron 200000 --threads 20 assembly.fasta /cluster/projects/nn8013k/opt/profileDB/pfam_profile predsResults_s7.5_5k_ni2_slice_mt0.4_me1 tempFolder 

MMseqs Version:                                             	6.a5d39d9
Substitution matrix                                         	aa:blosum62.out,nucl:nucleotide.out
Add backtrace                                               	false
Alignment mode                                              	2
Alignment mode                                              	0
Allow wrapped scoring                                       	false
E-value threshold                                           	100
Seq. id. threshold                                          	0
Min alignment length                                        	0
Seq. id. mode                                               	0
Alternative alignments                                      	0
Coverage threshold                                          	0
Coverage mode                                               	0
Max sequence length                                         	65535
Compositional bias                                          	1
Compositional bias                                          	1
Max reject                                                  	2147483647
Max accept                                                  	2147483647
Include identical seq. id.                                  	false
Preload mode                                                	0
Pseudo count a                                              	substitution:1.100,context:1.400
Pseudo count b                                              	substitution:4.100,context:5.800
Score bias                                                  	0
Realign hits                                                	false
Realign score bias                                          	-0.2
Realign max seqs                                            	2147483647
Correlation score weight                                    	0
Gap open cost                                               	aa:11,nucl:5
Gap extension cost                                          	aa:1,nucl:2
Zdrop                                                       	40
Threads                                                     	20
Compressed                                                  	0
Verbosity                                                   	3
Seed substitution matrix                                    	aa:VTML80.out,nucl:nucleotide.out
Sensitivity                                                 	7.5
k-mer length                                                	0
k-score                                                     	seq:2147483647,prof:2147483647
Alphabet size                                               	aa:21,nucl:5
Max results per query                                       	5000
Split database                                              	0
Split mode                                                  	2
Split memory limit                                          	0
Diagonal scoring                                            	true
Exact k-mer matching                                        	0
Mask residues                                               	1
Mask residues probability                                   	0.9
Mask lower case residues                                    	0
Minimum diagonal score                                      	15
Spaced k-mers                                               	1
Spaced k-mer pattern                                        	
Local temporary path                                        	
Rescore mode                                                	0
Remove hits by seq. id. and coverage                        	false
Sort results                                                	0
Mask profile                                                	1
Profile E-value threshold                                   	0.001
Global sequence weighting                                   	false
Allow deletions                                             	false
Filter MSA                                                  	1
Use filter only at N seqs                                   	0
Maximum seq. id. threshold                                  	0.9
Minimum seq. id.                                            	0.0
Minimum score per column                                    	-20
Minimum coverage                                            	0
Select N most diverse seqs                                  	1000
Pseudo count mode                                           	0
Gap pseudo count                                            	10
Min codons in orf                                           	15
Max codons in length                                        	32734
Max orf gaps                                                	2147483647
Contig start mode                                           	2
Contig end mode                                             	2
Orf start mode                                              	1
Forward frames                                              	1,2,3
Reverse frames                                              	1,2,3
Translation table                                           	1
Translate orf                                               	0
Use all table starts                                        	false
Offset of numeric ids                                       	0
Create lookup                                               	0
Add orf stop                                                	false
Overlap between sequences                                   	0
Sequence split mode                                         	1
Header split mode                                           	0
Chain overlapping alignments                                	0
Merge query                                                 	1
Search type                                                 	0
Search iterations                                           	2
Start sensitivity                                           	4
Search steps                                                	1
Exhaustive search mode                                      	false
Filter results during exhaustive search                     	0
Strand selection                                            	1
LCA search mode                                             	false
Disk space limit                                            	0
MPI runner                                                  	
Force restart with latest tmp                               	false
Remove temporary files                                      	false
maximal combined evalue of an optimal set                   	1
minimal length ratio between combined optimal set and target	0.4
Maximal intron length                                       	200000
Minimal intron length                                       	15
Minimal exon length aa                                      	11
Maximal overlap of exons                                    	10
Maximal number of exon sets                                 	1
Gap open penalty                                            	-1
Gap extend penalty                                          	-1
allow same-strand overlaps                                  	0
translate codons to AAs                                     	0
write target key instead of accession                       	0
write fragment contig coords                                	0
Reverse AA Fragments                                        	0

createdb /cluster/projects/nn9244k/olekto/projects/gene_familiy_annotation/results/pfam_metaeuk_all/Gadus_morhua.gadMor3.0.dna_sm.toplevel.fa tempFolder/6466159516689474313/contigs --dbtype 2 --compressed 0 -v 3 

Converting sequences
[
Time for merging to contigs_h: 0h 0m 0s 63ms
Time for merging to contigs: 0h 0m 1s 94ms
Database type: Nucleotide
Time for processing: 0h 0m 3s 441ms
Create directory tempFolder/6466159516689474313/tmp_predict
Enforcing exhaustive profile search mode due to profile target database
predictexons tempFolder/6466159516689474313/contigs /cluster/projects/nn8013k/opt/profileDB/pfam_profile tempFolder/6466159516689474313/MetaEuk_calls tempFolder/6466159516689474313/tmp_predict --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 0 --alignment-mode 2 --alignment-output-mode 0 --wrapped-scoring 0 -e 100 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 20 --compressed 0 -v 3 --seed-sub-mat 'aa:VTML80.out,nucl:nucleotide.out' -s 7.5 -k 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seqs 5000 --split 0 --split-mode 2 --split-memory-limit 0 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-prob 0.9 --mask-lower-case 0 --min-ungapped-score 15 --spaced-kmer-mode 1 --rescore-mode 0 --filter-hits 0 --sort-results 0 --mask-profile 1 --e-profile 0.001 --wg 0 --allow-deletion 0 --filter-msa 1 --filter-min-enable 0 --max-seq-id 0.9 --qid '0.0' --qsc -20 --cov 0 --diff 1000 --pseudo-cnt-mode 0 --gap-pc 10 --min-length 15 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 0 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --add-orf-stop 0 --sequence-overlap 0 --sequence-split-mode 1 --headers-split-mode 0 --chain-alignments 0 --merge-query 1 --search-type 0 --num-iterations 2 --start-sens 4 --sens-steps 1 --exhaustive-search 0 --exhaustive-search-filter 0 --strand 1 --lca-search 0 --disk-space-limit 0 --force-reuse 0 --remove-tmp-files 0 --metaeuk-eval 1 --metaeuk-tcov 0.4 --max-intron 200000 --min-intron 15 --min-exon-aa 11 --max-overlap 10 --max-exon-sets 1 --set-gap-open -1 --set-gap-extend -1 --reverse-fragments 0 

extractorfs /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/contigs /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/nucl_6f --min-length 15 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 0 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --threads 20 --compressed 0 -v 3 

[=================================================================] 226 4s 59ms
Time for merging to nucl_6f_h: 0h 0m 7s 271ms
Time for merging to nucl_6f: 0h 0m 11s 803ms
Time for processing: 0h 0m 32s 731ms
translatenucs /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/nucl_6f /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/aa_6f --translation-table 1 --add-orf-stop 0 -v 3 --compressed 0 --threads 20 

[=================================================================] 26.11M 11s 136ms
Time for merging to aa_6f: 0h 0m 12s 521ms
Time for processing: 0h 0m 25s 141ms
Create directory /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search
search /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/aa_6f /cluster/projects/nn8013k/opt/profileDB/pfam_profile /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/search_res /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 0 --alignment-mode 2 --alignment-output-mode 0 --wrapped-scoring 0 -e 100 --min-seq-id 0 --min-aln-len 11 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 20 --compressed 0 -v 3 --seed-sub-mat 'aa:VTML80.out,nucl:nucleotide.out' -s 7.5 -k 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seqs 5000 --split 0 --split-mode 2 --split-memory-limit 0 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-prob 0.9 --mask-lower-case 0 --min-ungapped-score 15 --spaced-kmer-mode 1 --rescore-mode 0 --filter-hits 0 --sort-results 0 --mask-profile 1 --e-profile 0.001 --wg 0 --allow-deletion 0 --filter-msa 1 --filter-min-enable 0 --max-seq-id 0.9 --qid '0.0' --qsc -20 --cov 0 --diff 1000 --pseudo-cnt-mode 0 --gap-pc 10 --min-length 15 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 0 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --add-orf-stop 0 --sequence-overlap 0 --sequence-split-mode 1 --headers-split-mode 0 --chain-alignments 0 --merge-query 1 --search-type 0 --num-iterations 2 --start-sens 4 --sens-steps 1 --exhaustive-search 1 --exhaustive-search-filter 0 --strand 1 --lca-search 0 --disk-space-limit 0 --force-reuse 0 --remove-tmp-files 0 

prefilter /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/profileDB /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/aa_6f /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/pref --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --seed-sub-mat 'aa:VTML80.out,nucl:nucleotide.out' -s 7.5 -k 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 26108213 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --comp-bias-corr-scale 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-prob 0.9 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 20 --compressed 0 -v 3 

Query database size: 19482 type: Profile
Estimated memory consumption: 37G
Target database size: 26108213 type: Aminoacid
Index table k-mer threshold: 0 at k-mer size 6 
Index table: counting k-mers
[=================================================================] 26.11M 12s 127ms
Index table: Masked residues: 100402825
Index table: fill
[=================================================================] 26.11M 10s 753ms
Index statistics
Entries:          685153999
DB size:          4408 MB
Avg k-mer size:   10.705531
Top 10 k-mers
    GVLFGR	18091
    KNSTVF	17287
    KKIGVV	16264
    PINSPY	14718
    SLLLSL	12316
    VLLFMT	12208
    LSSSLS	11369
    MKNRTV	11171
    VMKINT	10673
    LPMFTT	9803
Time for index table init: 0h 0m 25s 44ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 88
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 19482
Target db start 1 to 26108213
[=================================================================] 19.48K 1m 36s 112ms

1224.557738 k-mers per position
2006360 DB matches per sequence
0 overflows
0 queries produce too many hits (truncated result)
40786 sequences passed prefiltering per query sequence
29414 median result list length
5 sequences with 0 size result lists
Time for merging to pref: 0h 0m 0s 31ms
Time for processing: 0h 2m 3s 347ms
result2stats /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/profileDB /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/aa_6f /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/pref /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/pref_count.tsv --stat linecount --tsv --threads 20 --compressed 0 -v 3 

[=================================================================] 19.48K 2s 273ms
Time for merging to pref_count.tsv: 0h 0m 0s 41ms
Time for processing: 0h 0m 2s 592ms
align /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/profileDB /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/aa_6f /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/pref /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/aln --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 1 --alignment-mode 2 --alignment-output-mode 1 --wrapped-scoring 0 -e 134012 --min-seq-id 0 --min-aln-len 11 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 20 --compressed 0 -v 3 

Compute score, coverage and sequence identity
Query database size: 19482 type: Profile
Target database size: 26108213 type: Aminoacid
Calculation of alignments
[=================================================================] 19.48K 10m 5s 252ms
Time for merging to aln: 0h 0m 0s 31ms
794609252 alignments calculated
52520709 sequence pairs passed the thresholds (0.066096 of overall calculated)
2695.858154 hits per query sequence
Time for processing: 0h 10m 9s 250ms
rmdb /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/pref -v 3 

Time for processing: 0h 0m 1s 155ms
mvdb /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/aln /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/aln_merged -v 3 

Time for processing: 0h 0m 0s 13ms
align /cluster/projects/nn8013k/opt/profileDB/pfam_profile /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/aa_6f /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/aln_merged /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/aln --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 1 --alignment-mode 2 --alignment-output-mode 0 --wrapped-scoring 0 -e 134012 --min-seq-id 0 --min-aln-len 11 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 20 --compressed 0 -v 3 

Compute score, coverage and sequence identity
Query database size: 19482 type: Profile
Target database size: 26108213 type: Aminoacid
Calculation of alignments
[=================================================================] 19.48K 1m 44s 370ms
Time for merging to aln: 0h 0m 0s 31ms
52520709 alignments calculated
52520709 sequence pairs passed the thresholds (1.000000 of overall calculated)
2695.858154 hits per query sequence
Time for processing: 0h 1m 46s 77ms
rmdb /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/aln_merged -v 3 

Time for processing: 0h 0m 0s 54ms
swapresults /cluster/projects/nn8013k/opt/profileDB/pfam_profile /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/aa_6f /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/tmp_search/2475110616106612820/aln /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/search_res --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -e 1.79769e+308 --split-memory-limit 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --threads 20 --compressed 0 --db-load-mode 0 -v 3 

Computing offsets.
[=================================================================] 19.48K 1s 77ms

Reading results.
[=================================================================] 19.48K 1s 103ms

Output database: /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/search_res
[=================================================================] 26.11M 7s 715ms

Time for merging to search_res: 0h 0m 12s 495ms
Time for processing: 0h 0m 23s 865ms
resultspercontig /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/contigs /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/nucl_6f /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/search_res /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/search_res_by_contig --threads 20 --compressed 0 -v 3 

Computing ORF lookup
Computing contig offsets
Computing contig lookup
Time for contig lookup: 0h 0m 1s 767ms
=====[============================================================] 226 20s 997ms
Time for merging to search_res_by_contig: 0h 0m 0s 24ms
Time for processing: 0h 0m 25s 794ms
collectoptimalset /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/search_res_by_contig /cluster/projects/nn8013k/opt/profileDB/pfam_profile /cluster/work/users/olekto/metaeuk/230102_093906/tempFolder/6466159516689474313/tmp_predict/18356170210691509079/dp_predictions --metaeuk-eval 1 --metaeuk-tcov 0.4 --max-intron 200000 --min-intron 15 --min-exon-aa 11 --max-overlap 10 --max-exon-sets 1 --set-gap-open -1 --set-gap-extend -1 --score-bias 0 --threads 20 --compressed 0 -v 3 

[there should be 20 columns in the input file. This doesn't seem to be the case.
there should be 20 columns in the input file. This doesn't seem to be the case.
there should be 20 columns in the input file. This doesn't seem to be the case.
Error: collectoptimalset step died
Error: predictexons step died

## Context
I want to evaluate the use of PFAM profiles for general annotation of whole genomes. HMMER is much to slow, but it looks like mmseqs2/metaeuk is much faster, but maybe less sensitive. Running without --num-iterations works fine, but picks up much fewer hits than hmmer for a couple domains with I am familiar with. I had hoped that adding --num-iterations would increase what I find, but it stops with the above error message.

## Your Environment
metaeuk Version: 6.a5d39d9
Installed via conda.

Thank you.

Ole

**Comment by elileka** [comment]
Hi Ole,

This mode of profile search is not compatible with MetaEuk. We should actually block it.

You could try increasing the sensitivity parameter. Depending on your case, perhaps using --max-exon-sets > 1 can be useful for you. https://github.com/soedinglab/metaeuk#optional-calling-of-sub-optimal-exon-sets

Another option is to explore single-exon matches to your profiles using MMseqs2 only (can be run through MetaEuk). If you just run a profile search you can use the iteration parameter.

Best,
Eli

**Comment by olekto** [comment]
Hi Eli,
thank you for your answer. I'll take a look at those alternatives.

Ole

**Comment by elileka** [comment]
Thank you for the issue. We fixed the code so that modifying that parameter is no longer possible.
