### ISSUE TITLE
easypredict.sh error 13 (Permission denied)

### ISSUE THREAD

**Issue by laxeye** [soedinglab/metaeuk#79]
## Expected Behavior
The pipeline works.

## Current Behavior
The pipeline doesn't work. Error when easypredict.sh starts.

### I
metaeuk easy-predict genomic/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fna ~/Data/DB/mmseqs/odb10_fungi.mmseq easy-predict/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.default.10.faa tmp
(genome available at NCBI)

### II
sh tmp/8151178090008839435/easypredict.sh genomic/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fna ~/Data/DB/mmseqs/odb10_fungi.mmseq easy-predict/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.default.10.faa tmp

### III
export MMSEQS="metaeuk"
sh tmp/8151178090008839435/easypredict.sh genomic/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fna ~/Data/DB/mmseqs/odb10_fungi.mmseq easy-predict/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.default.10.faa tmp

### I
Create directory tmp
easy-predict genomic/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fna /home/korzheg/Data/DB/mmseqs/odb10_fungi.mmseq easy-predict/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.default.10.faa tmp 

MMseqs Version:                                             	6.a5d39d9
<...>
Reverse AA Fragments                                        	0

Failed to execute tmp/8151178090008839435/easypredict.sh with error 13.

### II
tmp/8151178090008839435/easypredict.sh: 33: : Permission denied
Error: contigs createdb died

### III
createdb genomic/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fna tmp/contigs --dbtype 2 

MMseqs Version:       	6.a5d39d9
Database type         	2
Shuffle input database	true
Createdb mode         	0
Write lookup file     	1
Offset of numeric ids 	0
Compressed            	0
Verbosity             	3

Converting sequences
[405] 0s 3ms
Time for merging to contigs_h: 0h 0m 0s 0ms
Time for merging to contigs: 0h 0m 0s 17ms
Database type: Nucleotide
Time for processing: 0h 0m 0s 81ms
Create directory tmp/tmp_predict
predictexons tmp/contigs /home/korzheg/Data/DB/mmseqs/odb10_fungi.mmseq tmp/MetaEuk_calls tmp/tmp_predict 

MMseqs Version:                                             	6.a5d39d9
<...>
Reverse AA Fragments                                        	0

Failed to execute tmp/tmp_predict/16621461692745561225/predictexons.sh with error 13.
Error: predictexons step died

So, the createdb step was done, but the next (predictexons) couldn't start.

## Context
The 33rd line of tmp/8151178090008839435/easypredict.sh is:
`    "$MMSEQS" createdb "${USER_INPUT_CONTIGS}" "${TMP_PATH}/contigs" --dbtype 2 ${VERBOSITY_COMP_PAR} \`
and MMSEQS variable isn't defined. 

I defined MMSEQS variable by `export MMSEQS="metaeuk"` but it works only once at easypredict step.

## Your Environment
* metaeuk Version: 6.a5d39d9 (installed via conda in new environment)
* AMD Ryzen 3900
* Ubuntu 22.04.2 LTS

**Comment by milot-mirdita** [comment]
Does the file system in which your tmp directories are placed Happen to be mounted with the `noexec` flag? You should be able to check in the `/etc/fstab`file.

If so please specify a different directory in a different file system.

Also please don't try to execute the generated `.sh` files directly. Metaeuk sets up many different environment variables that are needed for correct execution.
