### ISSUE TITLE
Build fails on some architectures: ld: error: undefined symbol: roundevenf

### ISSUE THREAD

**Issue by yurivict** [soedinglab/metaeuk#85]
Build fails on i386, armv7, powerpc64le architectures:
```
ld: error: undefined symbol: roundevenf
>>> referenced by CSProfile.cpp
>>>               CSProfile.cpp.o:(float* CSProfile::computeProfile<2>(unsigned char*, int, float*, float*, float, float, float)) in archive lib/mmseqs/src/libmmseqs-framework.a
>>> referenced by CSProfile.cpp
>>>               CSProfile.cpp.o:(float* CSProfile::computeProfile<2>(unsigned char*, int, float*, float*, float, float, float)) in archive lib/mmseqs/src/libmmseqs-framework.a
>>> referenced by CSProfile.cpp
>>>               CSProfile.cpp.o:(float* CSProfile::computeProfile<2>(unsigned char*, int, float*, float*, float, float, float)) in archive lib/mmseqs/src/libmmseqs-framework.a
>>> referenced 13 more times
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Version: 6
clang-16
FreeBSD 14.0

**Comment by milot-mirdita** [comment]
32-bit platforms are not supported and produce wrong results. ppc64le should work, but that looks like some missing linked library?

**Comment by yurivict** [comment]
The roundevenf symbol seems to be related to the bundled simde library.
It is supposedly a compiler built-in function.

**Comment by milot-mirdita** [comment]
If not a built in then it uses the libm version. I see that glibc added it only some years ago. Maybe the BSD libc doesn’t have roundf implemented? We might also not explicitly link to libm, though I thought I fixed that issue a while ago.

**Comment by yurivict** [comment]
roundf is present in the FreeBSD's libm, but the problem is in a different function roundevenf.
roundevenf isn't called directly, only through simde.

**Comment by pkubaj** [comment]
@yurivict 
Are you sure it fails on powerpc64 as well? Here's my build log:
[metaeuk-6_2.log](https://github.com/soedinglab/metaeuk/files/13911290/metaeuk-6_2.log)

@milot-mirdita 
This bug raport is about ppc64, not ppc64le.

**Comment by yurivict** [comment]
The failures are on powerpc64le.

**Comment by yurivict** [comment]
Oh, I am very sorry!

powerpc64le has a different error and it is a clang crash.
I'll report it to the FreeBSD;s toolchain support.

**Comment by milot-mirdita** [comment]
ppc64 (big-endian) should also not work, only a very limited number of modules are big endian compatible. Metaeuk definitely uses modules that don't work (correctly) on big-endian.

**Comment by milot-mirdita** [comment]
Just out of curiosity, where is the compiler crash?

**Comment by yurivict** [comment]
[Here](https://pkg-status.freebsd.org/foul2/data/main-powerpc64le-default/pff89313922da_s51e7276365/logs/metaeuk-6_2.log) is the log.

**Comment by milot-mirdita** [comment]
```
Attributes 'zeroext and signext' are incompatible!
ptr @omp_get_proc_bind
fatal error: error in backend: Broken module found, compilation aborted!
```

this suggests an issue with libomp/openmp. 

The proc bind call is not really necessary, it’s just there to find out if we are in a somewhat common performance failure case and warn about it.

**Comment by pkubaj** [comment]
That looks like https://github.com/llvm/llvm-project/issues/63807

**Comment by mr-c** [comment]
If this is still happening, we are happy to receive patches to SIMDe to skip the `__builtin` checks (and use our portable fallbacks) for C23 features on platforms where certain libc libraries do not implement them. Obviously, working with the libc providers to add the missing functions is even better.
