### ISSUE TITLE
Error using `--add-orf-stop`

### ISSUE THREAD

**Issue by berkelem** [soedinglab/metaeuk#88]
Hi, I am encountering an error when I add the `--add-orf-stop` option to a `metaeuk easy-predict` run.

Here's my command: 
```
metaeuk easy-predict --threads 12 GCA_000192795.1_Vavr_culi_floridensis_V1_genomic.fna busco_downloads/lineages/fungi_odb10/refseq_db.faa test_output.fna tmp/ --max-intron 60000 --max-seq-len 70000 --min-exon-aa 15 --max-overlap 15 --min-intron 5 --overlap 1 --add-orf-stop -s 4.5
```
This works fine without the `--add-orf-stop` option, but once I add it in I get

```
ERROR: strand is MINUS but the contig coordinates are positive. Soemthing is wrong.
```
The relevant line in the code base is https://github.com/soedinglab/metaeuk/blob/master/src/exonpredictor/unitesetstofasta.cpp#L61

Might this be a bug?

**Comment by elileka** [comment]
Hi,

Hmm. Thank you, this needs checking...

Could you please provide us with the input so we can try to reproduce the problem?

Thank you

**Comment by elileka** [comment]
Hi,

I was able to reproduce your problem. The parameter you set is an MMseqs2 parameter, which should be blocked from MetaEuk because it messes it up. But I think you can actually get the info you need about stop codons by setting the MetaEuk param instead:
 --write-frag-coords 1.
 
 Thank you for reporting this!
 
Best,
Eli

**Comment by elileka** [comment]
The MMseqs2 parameter was blocked in the latest commit (6643). Please use --write-frag-coords 1 for information about stop codon positions.

**Comment by berkelem** [comment]
Thanks!

**Comment by elileka** [comment]
and sorry for your inconvenience... :-/
